---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: '使用SnapCenter备份 SQL Server 系统和用户数据库需要您选择资源类型，例如数据库、SQL 服务器实例和可用性组 (AG)。利用快照技术来创建资源所在卷的在线、只读副本。' 
---
= 支持的备份类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用SnapCenter备份 SQL Server 系统和用户数据库需要您选择资源类型，例如数据库、SQL 服务器实例和可用性组 (AG)。利用快照技术来创建资源所在卷的在线、只读副本。

您可以选择仅复制选项来指定 SQL Server 不截断事务日志。当您使用其他备份应用程序管理 SQL Server 时，应该使用此选项。保持事务日志完整可使任何备份应用程序恢复系统数据库。仅复制备份与计划备份的顺序无关，并且不会影响数据库的备份和还原过程。

|===
| 备份类型 | 描述 | 具有备份类型的仅复制选项 


 a| 
完整备份和日志备份
 a| 
备份系统数据库并截断事务日志。

SQL Server 通过删除已提交到数据库的条目来截断事务日志。

完整备份完成后，此选项会创建一个捕获事务信息的事务日志。通常，您应该选择此选项。但是，如果您的备份时间很短，您可以选择不运行事务日志备份，而是进行完整备份。

您不能为 master 和 msdb 系统数据库创建日志备份。但是，您可以为模型系统数据库创建日志备份。
 a| 
备份系统数据库文件和事务日志而不截断日志。

仅复制备份不能作为差异基准或差异备份，并且不会影响差异基准。恢复仅复制完整备份与恢复任何其他完整备份相同。



 a| 
完整数据库备份
 a| 
备份系统数据库文件。

您可以为主数据库、模型数据库和 msdb 系统数据库创建完整的数据库备份。
 a| 
备份系统数据库文件。



 a| 
事务日志备份
 a| 
备份截断的事务日志，仅复制自最近的事务日志备份以来提交的事务。

如果您安排频繁的事务日志备份和完整的数据库备份，则可以选择粒度恢复点。
 a| 
备份事务日志而不截断它们。

此备份类型不会影响常规日志备份的顺序。仅复制日志备份对于执行在线恢复操作很有用。

|===