---
permalink: protect-scsql/concept_requirements_for_restoring_a_database.html 
sidebar: sidebar 
keywords: Requirements 
summary: 从SnapCenter Plug-in for Microsoft SQL Server 备份还原 SQL Server 数据库之前，必须确保满足几个要求。 
---
= 恢复数据库的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从SnapCenter Plug-in for Microsoft SQL Server 备份还原 SQL Server 数据库之前，必须确保满足几个要求。

* 恢复数据库之前，目标 SQL Server 实例必须处于在线且正在运行的状态。
+
这适用于用户数据库还原操作和系统数据库还原操作。

* 必须禁用针对您正在还原的 SQL Server 数据运行的SnapCenter操作，包括在远程管理或远程验证服务器上安排的任何作业。
* 如果系统数据库不起作用，则必须首先使用 SQL Server 实用程序重建系统数据库。
* 如果您正在安装该插件，请确保授予其他角色恢复可用性组 (AG) 备份的权限。
+
当满足以下条件之一时，恢复 AG 会失败：

+
** 如果插件由 RBAC 用户安装，并且管理员尝试还原 AG 备份
** 如果插件由管理员安装，并且 RBAC 用户尝试还原 AG 备份


* 如果要将自定义日志目录备份还原到备用主机，则SnapCenter服务器和插件主机必须安装相同的SnapCenter版本。
* 您必须安装 Microsoft 修补程序 KB2887595。  Microsoft 支持站点包含有关 KB2887595 的更多信息。
+
https://support.microsoft.com/kb/2887595["Microsoft 支持文章 2887595：Windows RT 8.1、Windows 8.1 和 Windows Server 2012 R2 更新汇总：2013 年 11 月"]

* 您必须已备份资源组或数据库。
* 如果您要将快照复制到镜像或保管库， SnapCenter管理员必须已为源卷和目标卷分配存储虚拟机 (SVM)。
+
有关管理员如何向用户分配资源的信息，请参阅SnapCenter安装信息。

* 恢复数据库之前必须停止所有备份和克隆作业。
* 如果数据库大小为数以 TB 为单位，则还原操作可能会超时。
+
您必须通过运行以下命令将SnapCenter Server 的 RESTTimeout 参数值增加到 20000000 毫秒：Set-SmConfigSettings -Agent -configSettings @{"RESTTimeout" = "20000000"}。根据数据库的大小，可以更改超时值，可以设置的最大值为 86400000 毫秒。



如果您想在数据库在线时进行恢复，则应在“恢复”页面中启用在线恢复选项。
