---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: 使用SnapCenter，您可以从资源组或数据库创建克隆。您可以执行按需克隆，也可以安排资源组或数据库的重复克隆操作。如果您定期克隆备份，则可以使用该克隆来开发应用程序、填充数据或恢复数据。 
---
= 执行克隆生命周期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用SnapCenter，您可以从资源组或数据库创建克隆。您可以执行按需克隆，也可以安排资源组或数据库的重复克隆操作。如果您定期克隆备份，则可以使用该克隆来开发应用程序、填充数据或恢复数据。

SnapCenter使您能够安排多个克隆操作在多个服务器上同时运行。

.开始之前
* 克隆到独立数据库实例时，请确保挂载点路径存在并且是专用磁盘。
* 克隆到故障转移群集实例 (FCI) 时，请确保挂载点存在、它是共享磁盘，并且路径和 FCI 应该属于同一个 SQL 资源组。
* 如果源数据库或目标实例位于集群共享卷（csv）上，则克隆的数据库将位于 csv 上。



NOTE: 对于虚拟环境（VMDK/RDM），确保挂载点是专用磁盘。

.关于此任务
* SCRIPTS_PATH 是使用插件主机的 SMCoreServiceHost.exe.Config 文件中的 PredefinedWindowsScriptsDirectory 键定义的。
+
如果需要，您可以更改此路径并重新启动 SMcore 服务。为了安全起见，建议您使用默认路径。

+
可以通过 API 从 Swagger 显示该键的值：API /4.7/configsettings

+
您可以使用 GET API 来显示键的值。不支持 SET API。

* 克隆生命周期向导页面上的大多数字段都是不言自明的。以下信息描述了您可能需要指导的字段。
* 对于ONTAP 9.12.1 及以下版本，如果指定 Snapshot 锁定期限，则从防篡改快照创建的克隆将继承SnapLock到期时间。存储管理员应在SnapLock到期后手动清理克隆。


.步骤
. 在左侧导航窗格中，单击“*资源*”，然后从列表中选择适当的插件。
. 在资源页面中，从*视图*列表中选择*数据库*或*资源组*。
. 选择资源组或数据库，然后单击“克隆生命周期”。
. 在“选项”页面中，执行以下操作：
+
|===
| 对于这个领域... | 操作 


 a| 
克隆作业名称
 a| 
指定克隆生命周期作业名称，以帮助监控和修改克隆生命周期作业。



 a| 
克隆服务器
 a| 
选择要放置克隆的主机。



 a| 
克隆实例
 a| 
选择要将数据库克隆到的克隆实例。此 SQL 实例必须位于指定的克隆服务器中。



 a| 
克隆后缀
 a| 
输入将附加到克隆数据库的后缀，以标识它是一个克隆。用于创建克隆资源组的每个 SQL 实例都必须具有唯一的数据库名称。例如，如果克隆资源组包含来自 SQL 实例“inst1”的源数据库“db1”，并且如果“db1”被克隆到“inst1”，则克隆数据库名称应该是“db1__clone”。 “`__clone`” 是强制的用户定义后缀，因为数据库被克隆到同一个实例。如果将“`db1`”克隆到 SQL 实例“`inst2`”，则克隆数据库名称可以保留为“`db1`”（后缀是可选的），因为数据库被克隆到不同的实例。



 a| 
自动分配挂载点或自动分配路径下的卷挂载点
 a| 
选择是否自动分配路径下的挂载点或卷挂载点。选择自动分配路径下的卷挂载点使您能够提供特定的目录。挂载点将在该目录内创建。在选择此选项之前，您必须确保目录为空。如果目录中存在数据库，则挂载操作后数据库将处于无效状态。

|===
. 在位置页面中，选择用于创建克隆的存储位置。
. 在脚本页面中，分别输入克隆操作之前或之后应运行的前置脚本或后置脚本的路径和参数。
+
例如，您可以运行脚本来更新 SNMP 陷阱、自动发出警报、发送日志等。

+

NOTE: 前言或后记路径不应包含驱动器或共享。该路径应相对于 SCRIPTS_PATH。

+
默认脚本超时为 60 秒。

. 在“计划”页面中，执行以下操作之一：
+
** 如果您想立即执行克隆作业，请选择*立即运行*。
** 当您想要确定克隆操作发生的频率、克隆计划的开始时间、克隆操作发生的日期、计划的到期时间以及计划到期后是否必须删除克隆时，请选择*配置计划*。


. 在通知页面中，从*电子邮件首选项*下拉列表中，选择您想要发送电子邮件的场景。
+
您还必须指定发件人和收件人的电子邮件地址以及电子邮件的主题。如果您想附加执行的克隆操作的报告，请选择*附加作业报告*。

+

NOTE: 对于电子邮件通知，您必须使用 GUI 或 PowerShell 命令 Set-SmSmtpServer 指定 SMTP 服务器详细信息。

+
对于 EMS，您可以参考 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["管理 EMS 数据收集"]

. 查看摘要，然后单击“*完成*”。


您应该使用*Monitor* > *Jobs*页面来监控克隆过程。
