---
permalink: protect-scsql/task_install_the_snapcenter_plug_in_for_sql_server_silently.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: 您应该从SnapCenter用户界面中安装适用于 Microsoft SQL Server 的SnapCenter插件。但是，如果由于某种原因您无法这样做，您可以从 Windows 命令行以静默模式无人值守运行 SQL Server 插件安装程序。 
---
= 从命令行静默安装适用于 Microsoft SQL Server 的SnapCenter插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应该从SnapCenter用户界面中安装适用于 Microsoft SQL Server 的SnapCenter插件。但是，如果由于某种原因您无法这样做，您可以从 Windows 命令行以静默模式无人值守运行 SQL Server 插件安装程序。

.开始之前
* 安装之前，您必须删除适用于 Microsoft SQL Server 的早期版本的SnapCenter插件。
+
有关更多信息，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["如何从插件主机手动直接安装SnapCenter插件"^] 。



.步骤
. 验证插件主机上是否存在 C:\temp 文件夹以及登录用户是否对该文件夹具有完全访问权限。
. 从 C:\ProgramData\ NetApp\ SnapCenter\Package Repository 下载 SQL Server 软件插件。
+
可以从安装SnapCenter服务器的主机访问此路径。

. 将安装文件复制到要安装插件的主机上。
. 从本地主机上的 Windows 命令提示符，导航到保存插件安装文件的目录。
. 安装 SQL Server 软件插件：
+
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"Debug_Log_Path" /log"Log_Path" BI_SNAPCENTER_PORT=Num SUITE_INSTALLDIR="Install_Directory_Path" BI_SERVICEACCOUNT=domain\\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`

+
用您的数据替换占位符值

+
** Debug_Log_Path 是套件安装程序日志文件的名称和位置。
** Log_Path 是插件组件（SCW、SCSQL 和 SMCore）的安装日志的位置。
** Num 是SnapCenter与 SMCore 通信的端口
** Install_Directory_Path是主机插件包安装目录。
** domain\administrator 是适用于 Microsoft Windows Web 服务帐户的SnapCenter插件。
** password 是 Microsoft Windows Web 服务帐户的SnapCenter插件的密码。+ 
`"snapcenter_windows_host_plugin.exe"/silent /debuglog"C:\HPPW_SCSQL_Install.log" /log"C:\" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW,SCSQL`


+

NOTE: 安装 SQL Server 插件期间传递的所有参数都区分大小写。

. 监视 Windows 任务计划程序、主安装日志文件 C:\Installdebug.log 以及 C:\Temp 中的附加安装文件。
. 监视 %temp% 目录以验证 msiexe.exe 安装程序是否正在无错误地安装软件。
+

NOTE: SQL Server 插件的安装在主机上注册该插件，而不是在SnapCenter服务器上注册。您可以通过使用SnapCenter GUI 或 PowerShell cmdlet 添加主机在SnapCenter服务器上注册插件。添加主机后，会自动发现插件。


