---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter使用凭据对SnapCenter操作的用户进行身份验证。您应该创建用于安装SnapCenter插件的凭据以及用于在数据库或 Windows 文件系统上执行数据保护操作的附加凭据。 
---
= 为 Windows 的SnapCenter插件包设置凭据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter使用凭据对SnapCenter操作的用户进行身份验证。您应该创建用于安装SnapCenter插件的凭据以及用于在数据库或 Windows 文件系统上执行数据保护操作的附加凭据。

.开始之前
* 在安装插件之前，您必须设置 Windows 凭据。
* 您必须设置具有管理员权限的凭据，包括远程主机上的管理员权限。
* Windows 主机上的 SQL 身份验证
+
安装插件后，您必须设置 SQL 凭据。

+
如果您正在为 Microsoft SQL Server 部署SnapCenter插件，则必须在安装插件后设置 SQL 凭据。为具有 SQL Server sysadmin 权限的用户设置凭据。

+
SQL 身份验证方法针对 SQL Server 实例进行身份验证。这意味着必须在SnapCenter中发现 SQL Server 实例。因此，添加SQL凭证前，必须先添加主机、安装插件包、刷新资源。您需要 SQL Server 身份验证才能执行诸如调度或发现资源之类的操作。



.步骤
. 在左侧导航窗格中，单击“*设置*”。
. 在“设置”页面中，单击“*凭据*”。
. 单击“*新建*”。
. 在“凭据”页面中，指定配置凭据所需的信息：
+
|===
| 对于这个领域... | 操作 


 a| 
凭证名称
 a| 
输入凭证的名称。



 a| 
用户名/密码
 a| 
输入用于身份验证的用户名和密码。

** 域管理员
+
指定要安装SnapCenter插件的系统上的域管理员。用户名字段的有效格式为：

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** 本地管理员（仅适用于工作组）
+
对于属于工作组的系统，请在要安装SnapCenter插件的系统上指定内置的本地管理员。如果用户帐户具有提升的权限或主机系统上禁用了用户访问控制功能，则可以指定属于本地管理员组的本地用户帐户。用户名字段的有效格式为： `UserName`

+
请勿在密码中使用双引号（“）或反引号（`）。密码中不应同时使用小于号 (<) 和感叹号 (!) 符号。例如，lessthan<!10、lessthan10<!、backtick`12。





 a| 
认证模式
 a| 
选择您想要使用的身份验证模式。如果选择SQL身份验证模式，还必须指定SQL服务器实例以及SQL实例所在的主机。

|===
. 单击“*确定*”。


完成凭证设置后，您可能希望在“用户和访问”页面中将凭证维护分配给用户或用户组。
