---
permalink: protect-scsql/task-install-snapcenter-server-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: 提供安装适用于 Microsoft SQL Server 的SnapCenter服务器的说明。 
---
= 为 Microsoft SQL Server 安装SnapCenter服务器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
提供一套用于安装适用于 Microsoft SQL Server 的SnapCenter服务器的简明安装说明。



== 步骤 1：下载并安装SnapCenter服务器

. SnapCenter https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 支持站点"^]然后双击该exe。
+
启动安装后，将执行所有预检查，如果不满足最低要求，则会显示相应的错误或警告消息。您可以忽略警告消息并继续安装；但是，错误应该得到修复。

. 查看SnapCenter服务器安装所需的预填充值并根据需要进行修改。
+
您不必指定 MySQL 服务器存储库数据库的密码。在SnapCenter Server 安装期间，密码会自动生成。

+

NOTE: 自定义安装路径不支持特殊字符“%”。如果路径中包含“%”，安装将失败。

. 单击“立即安装”。




== 步骤 2：登录SnapCenter

. 从主机桌面上的快捷方式或安装提供的 URL 启动SnapCenter （_\https://server:8146_ 表示安装SnapCenter Server 的默认端口 8146）。
. 输入凭证。
+
对于内置域管理员用户名格式，请使用：_NetBIOS\<用户名>_ 或 _<用户名>@<域>_ 或 _<DomainFQDN>\<用户名>_。

+
对于内置本地管理员用户名格式，请使用 _<username>_。

. 单击“登录”。




== 步骤 3：添加基于SnapCenter Standard 控制器的许可证

. 使用ONTAP命令行登录控制器并输入：
+
`system license add -license-code <license_key>`

. 验证许可证：
+
`license show`





== 步骤 4：设置存储系统连接

. 在左侧窗格中，单击“存储系统”>“新建”。
. 在添加存储系统页面中，执行以下操作：
+
.. 输入存储系统的名称或IP地址。
.. 输入用于访问存储系统的凭据。
.. 选中复选框以启用事件管理系统 (EMS) 和AutoSupport。


. 如果要修改分配给平台、协议、端口和超时的默认值，请单击“*更多选项*”。
. 单击“*提交*”。

