---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: 您可以在使用SnapCenter备份 SQL Server 资源之前为资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。 
---
= 为 SQL Server 数据库创建备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用SnapCenter备份 SQL Server 资源之前为资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。

.开始之前
* 您必须已经定义了您的数据保护策略。
* 您必须通过完成安装SnapCenter、添加主机、识别资源和创建存储系统连接等任务来为数据保护做好准备。
* 您必须已配置主机日志目录以进行日志备份。
* 您必须刷新（发现）SQL Server 资源。
* 如果您要将快照复制到镜像或保管库， SnapCenter管理员必须已为您分配源卷和目标卷的存储虚拟机 (SVM)。
+
有关管理员如何向用户分配资源的信息，请参阅SnapCenter安装信息。

* 如果您想在前脚本和后脚本中运行 PowerShell 脚本，则应在 web.config 文件中将 usePowershellProcessforScripts 参数的值设置为 true。
+
默认值为 false。

* 查看SnapMirror主动同步特定的先决条件和限制。欲了解详细信息，请参阅 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror主动同步的对象限制"]。


.关于此任务
* 备份策略是一组规则，用于控制如何管理和保留备份以及资源或资源组的备份频率。此外，您还可以指定复制和脚本设置。当您想要将策略重新用于另一个资源组时，在策略中指定选项可以节省时间。
+
SCRIPTS_PATH 是使用插件主机的 SMCoreServiceHost.exe.Config 文件中的 PredefinedWindowsScriptsDirectory 键定义的。

+
如果需要，您可以更改此路径并重新启动 SMcore 服务。为了安全起见，建议您使用默认路径。

+
可以通过 API 从 Swagger 显示该键的值：API /4.7/configsettings

+
您可以使用 GET API 来显示键的值。不支持 SET API。

* SnapLock
+
** 如果选择了“保留备份副本特定天数”选项，则SnapLock保留期必须小于或等于上述保留天数。
+
指定快照锁定期可防止在保留期到期之前删除快照。这可能导致保留的快照数量超过策略中指定的数量。

+
对于ONTAP 9.12.1 及以下版本、作为恢复的一部分从SnapLock Vault 快照创建的克隆将继承SnapLock Vault 到期时间。存储管理员应在SnapLock到期后手动清理克隆。







== 步骤 1：创建策略名称

. 在左侧导航窗格中，选择“*设置*”。
. 在设置页面中，选择*策略*。
. 选择“*新建*”。
. 在*名称*页面中，输入策略名称和详细信息。




== 步骤 2：配置策略选项

. 在“策略类型”页面中，执行以下步骤：
+
.. 选择您的存储类型。
.. 选择您的政策范围。
+
[role="tabbed-block"]
====
.完整备份和日志备份
--
备份数据库文件和事务日志并截断事务日志。

... 选择*完整备份和日志备份*。
... 输入每个快照应备份的数据库的最大数量。
+

NOTE: 如果要同时运行多个备份操作，则必须增加此值。



--
.完整备份
--
备份数据库文件。

... 选择*完整备份*。
... 输入每个快照应备份的数据库的最大数量。默认值为 100
+

NOTE: 如果要同时运行多个备份操作，则必须增加此值。



--
.日志备份
--
... 备份事务日志。
... 选择*日志备份*。


--
.仅复制备份
--
... 如果您使用其他备份应用程序备份资源，请选择*仅复制备份*。


保持事务日志完整允许任何备份应用程序恢复数据库。通常，您不应在任何其他情况下使用仅复制选项。


NOTE: Microsoft SQL 不支持将“仅复制备份”选项与“完整备份和日志备份”选项一起用于辅助存储。

--
====






== 步骤 3：配置可用性组设置

. 在可用性组设置部分中，执行以下操作：
+
.. 仅在首选备份副本上备份。
+
选择此选项仅在首选备份副本上备份。首选备份副本由 SQL Server 中为 AG 配置的备份首选项决定。

.. 选择要备份的副本。
+
选择主 AG 副本或辅助 AG 副本进行备份。

.. 选择备份优先级（最小和最大备份优先级）
+
指定最小备份优先级数和最大备份优先级数，以决定要备份的 AG 副本。例如，最小优先级可以为 10，最大优先级可以为 50。在这种情况下，所有优先级大于 10 且小于 50 的 AG 副本都被视为备份。

+
默认情况下，最小优先级为 1，最大优先级为 100。



+

NOTE: 在集群配置中，备份根据策略中设置的保留设置保留在集群的每个节点上。如果 AG 的所有者节点发生变化，则根据保留设置进行备份，并且将保留前一个所有者节点的备份。  AG 的保留仅适用于节点级别。





== 步骤 4：配置快照和复制设置

. 在“快照和复制”页面中，执行以下步骤：
+
.. 通过选择*按需*、*每小时*、*每日*、*每周*或*每月*来指定计划类型。
+
一个策略只能选择一种计划类型。

+

NOTE: 您可以在创建资源组时指定备份操作的计划（开始日期、结束日期和频率）。这使您能够创建共享相同策略和备份频率的资源组，但允许您为每个策略分配不同的备份计划。

+

NOTE: 如果您已安排在凌晨 2:00，则夏令时 (DST) 期间不会触发该计划。







== 步骤 5：配置最新的保留设置

. 在“最新保留设置”部分中，根据备份类型页面中选择的备份类型，执行以下操作中的一项或多项：


[role="tabbed-block"]
====
.具体份数
--
仅保留特定数量的快照。

. 选择*保留适用于最近<number>天的日志备份*选项，并指定要保留的天数。如果接近此限制，您可能需要删除旧副本。


--
.具体天数
--
将备份副本保留特定天数。

. 选择*保留适用于最后<number>天完整备份的日志备份*选项，并指定保留日志备份副本的天数。


--
====


== 步骤 6：配置快照设置

. 对于完整备份保留设置，执行以下操作：
+
.. 指定要保留的快照总数
+
... 要指定要保留的快照数量，请选择*要保留的副本*。
... 如果快照数量超过指定数量，则会删除快照，并首先删除最旧的副本。
+

IMPORTANT: 默认情况下，保留计数的值设置为 2。如果将保留计数设置为 1，则保留操作可能会失败，因为第一个快照是SnapVault关系的参考快照，直到较新的快照复制到目标。

+

NOTE: 最大保留值为 1018。如果保留设置的值高于底层NetApp ONTAP版本支持的值，则备份将失败。







. 保留快照的时间长度
+
.. 如果您想指定在删除快照之前保留快照的天数，请选择“保留副本”****。


. 选择*Snapshot 副本锁定期限*并指定天、月或年的持续时间。
+
Snaplock 保留期应少于 100 年。

. 选择一个策略标签。
+

NOTE: 您可以为远程复制的主快照分配SnapMirror标签，从而允许主快照将快照复制操作从SnapCenter卸载到ONTAP二级系统。无需在策略页面中启用SnapMirror或SnapVault选项即可完成此操作。





== 步骤 7：配置辅助复制选项

. 在“选择辅助复制选项”部分中，选择以下一个或两个辅助复制选项：


[role="tabbed-block"]
====
.更新SnapMirror
--
创建本地 Snapshot 副本后更新SnapMirror 。

. 选择此选项可在另一个卷上创建备份集的镜像副本（SnapMirror）。
+
应为SnapMirror主动同步启用此选项。

+
在二次复制期间， SnapLock到期时间会加载主SnapLock到期时间。单击拓扑页面中的“*刷新*”按钮可刷新从ONTAP检索到的辅助和主SnapLock到期时间。

+
看link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在拓扑页面中查看 SQL Server 备份和克隆"] 。



--
.更新SnapVault
--
创建 Snapshot 副本后更新SnapVault 。

. 选择此选项可执行磁盘到磁盘的备份复制。
+
在二次复制期间， SnapLock到期时间会加载主SnapLock到期时间。单击拓扑页面中的“*刷新*”按钮可刷新从ONTAP检索到的辅助和主SnapLock到期时间。

+
当仅在ONTAP的辅助节点（称为SnapLock Vault）上配置SnapLock时，单击拓扑页面中的 *刷新* 按钮将刷新从ONTAP检索到的辅助节点上的锁定期。

+
有关SnapLock Vault 的更多信息，请参阅 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["将 Snapshot 副本提交到保管库目标上的 WORM"]

+
看link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在拓扑页面中查看 SQL Server 备份和克隆"] 。



--
.错误重试次数
--
. 输入进程停止之前应发生的复制尝试次数。


--
====


== 步骤 8：配置脚本设置

. 在脚本页面中，分别输入应在备份操作之前或之后运行的前置脚本或后置脚本的路径和参数。
+
例如，您可以运行脚本来更新 SNMP 陷阱、自动发出警报和发送日志。

+

NOTE: 前言或后记路径不应包含驱动器或共享。该路径应相对于 SCRIPTS_PATH。

+

NOTE: 您必须在ONTAP中配置SnapMirror保留策略，以便二级存储不会达到快照的最大限制。





== 步骤 9：配置验证设置

在验证页面中，执行以下步骤：

. 在“运行以下备份计划的验证”部分中，选择计划频率。
. 在数据库一致性检查选项部分中，执行以下操作：
+
.. 将完整性结构限制为数据库的物理结构（PHYSICAL_ONLY）
+
... 选择*将完整性结构限制为数据库的物理结构（PHYSICAL_ONLY）*以将完整性检查限制为数据库的物理结构，并检测影响数据库的页面撕裂、校验和失败以及常见硬件故障。


.. 抑制所有信息消息（NO INFOMSGS）
+
... 选择*抑制所有信息消息（NO_INFOMSGS）*以抑制所有信息消息。默认选择。


.. 显示每个对象报告的所有错误消息（ALL_ERRORMSGS）
+
... 选择*显示每个对象报告的所有错误消息（ALL_ERRORMSGS）*以显示每个对象报告的所有错误。


.. 不检查非聚集索引（NOINDEX）
+
... 如果不想检查非聚集索引，请选择“*不检查非聚集索引（NOINDEX）*”。  SQL Server 数据库使用 Microsoft SQL Server 数据库一致性检查器 (DBCC) 来检查数据库中对象的逻辑和物理完整性。


.. 限制检查并获取锁，而不是使用内部数据库快照（TABLOCK）
+
... 选择*限制检查并获取锁而不是使用内部数据库快照副本（TABLOCK）*来限制检查并获取锁而不是使用内部数据库快照。




. 在*日志备份*部分中，选择*完成后验证日志备份*以在完成后验证日志备份。
. 在*验证脚本设置*部分中，分别输入在验证操作之前或之后应运行的脚本或后脚本的路径和参数。
+

NOTE: 前言或后记路径不应包含驱动器或共享。该路径应相对于 SCRIPTS_PATH。





== 步骤 10：审核摘要

. 查看摘要，然后选择*完成*。

