---
permalink: protect-sco/alternate-ways-install-plug-in-linux-aix.html 
sidebar: sidebar 
keywords: alternate methods, install, plug-ins package, linux, aix, remote hosts, cmdlets, cluster host, silent mode, console mode 
summary: 您可以使用其他替代方法来安装适用于 Linux 的SnapCenter插件包或适用于 AIX 的SnapCenter插件包。 
---
= 安装 Linux 或 AIX 插件包的其他方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您还可以使用 cmdlet 或 CLI 手动安装适用于 Linux 或 AIX 的插件包。

在手动安装插件之前，您应该使用位于 _C:\ProgramData\ NetApp\ SnapCenter\Package Repository_ 的密钥 *snapcenter_public_key.pub* 和 *snapcenter_linux_host_plugin.bin.sig* 验证二进制包的签名。


NOTE: 确保要安装插件的主机上安装了 *OpenSSL 1.0.2g*。

通过运行以下命令验证二进制包的签名：

* 对于 Linux 主机： `openssl dgst -sha256 -verify snapcenter_public_key.pub -signature snapcenter_linux_host_plugin.bin.sig snapcenter_linux_host_plugin.bin`
* 对于 AIX 主机： `openssl dgst -sha256 -verify snapcenter_public_key.pub -signature snapcenter_aix_host_plugin.bsx.sig snapcenter_aix_host_plugin.bsx`




== 使用 cmdlet 在多个远程主机上安装

您应该使用 _Install-SmHostPackage_ PowerShell cmdlet 在多个主机上安装适用于 Linux 的SnapCenter插件包或适用于 AIX 的SnapCenter插件包。

*您需要什么*

您应该以域用户身份登录到SnapCenter ，并在要安装插件包的每个主机上拥有本地管理员权限。

*步骤*

. 启动 PowerShell。
. 在SnapCenter Server 主机上，使用 _Open-SmConnection_ cmdlet 建立会话，然后输入您的凭据。
. 使用 _Install-SmHostPackage_ cmdlet 和所需参数安装适用于 Linux 的SnapCenter插件包或适用于 AIX 的SnapCenter插件包。
+
当您已经手动安装了插件并且不想验证主机是否满足安装插件的要求时，可以使用_-skipprecheck_选项。

+

NOTE: 如果防火墙拒绝规则中指定了插件端口防火墙状态，则预检查脚本不会验证该状态。

. 输入您的远程安装凭据。


可以通过运行_Get-Help command_name_来获取有关可与 cmdlet 一起使用的参数及其描述的信息。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter软件 Cmdlet 参考指南"^]。



== 在集群主机上安装

您应该在集群主机的两个节点上安装适用于 Linux 的SnapCenter插件包或适用于 AIX 的SnapCenter插件包。

集群主机的每个节点都有两个IP。其中一个 IP 将是各个节点的公共 IP，第二个 IP 将是两个节点之间共享的集群 IP。

*步骤*

. 在集群主机的两个节点上安装适用于 Linux 的SnapCenter插件包或适用于 AIX 的SnapCenter插件包。
. 验证位于 _/var/opt/snapcenter/spl/etc/_ 的 spl.properties 文件中指定了 SNAPCENTER_SERVER_HOST、SPL_PORT、SNAPCENTER_SERVER_PORT 和 SPL_ENABLED_PLUGINS 参数的正确值。
+
如果 spl.properties 中未指定 SPL_ENABLED_PLUGINS，则可以添加它并分配值 SCO,SCU。

. 在SnapCenter Server 主机上，使用 _Open-SmConnection_ cmdlet 建立会话，然后输入您的凭据。
. 在每个节点中，使用 _Set-PreferredHostIPsInStorageExportPolicy_ sccli 命令和所需参数设置节点的首选 IP。
. 在SnapCenter Server 主机中，在 _C:\Windows\System32\drivers\etc\hosts_ 中添加集群 IP 和相应 DNS 名称的条目。
. 通过指定主机名的集群 IP，使用 _Add-SmHost_ cmdlet 将节点添加到SnapCenter服务器。


发现节点 1 上的 Oracle 数据库（假设集群 IP 托管在节点 1 上）并创建数据库的备份。如果发生故障转移，您可以使用在节点 1 上创建的备份来恢复节点 2 上的数据库。您还可以使用在节点 1 上创建的备份在节点 2 上创建克隆。


NOTE: 如果在运行任何其他SnapCenter操作时发生故障转移，则会出现过时的卷、目录和锁定文件。



== 静默模式下安装 Linux 插件包

您可以使用命令行界面 (CLI) 以静默模式安装适用于 Linux 的SnapCenter插件包。

*您需要什么*

* 您应该查看安装插件包的先决条件。
* 您应该确保未设置 DISPLAY 环境变量。
+
如果设置了 DISPLAY 环境变量，则应运行 unset DISPLAY，然后尝试手动安装插件。



*关于此任务*

在控制台模式下安装时，您需要提供必要的安装信息，而在静默模式下安装时，您不必提供任何安装信息。

*步骤*

. 从SnapCenter服务器安装位置下载适用于 Linux 的SnapCenter插件包。
+
默认安装路径为_C:\ProgramData\ NetApp\ SnapCenter\PackageRepository_。可以从安装SnapCenter服务器的主机访问此路径。

. 从命令提示符处，导航到下载安装文件的目录。
. 运行
+
`./SnapCenter_linux_host_plugin.bin-i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path`

. 编辑位于 _/var/opt/snapcenter/spl/etc/_ 的 spl.properties 文件以添加 SPL_ENABLED_PLUGINS=SCO,SCU，然后重新启动SnapCenter插件Loader服务。



IMPORTANT: 插件包的安装会在主机上注册插件，而不是在SnapCenter服务器上注册。您应该通过使用SnapCenter GUI 或 PowerShell cmdlet 添加主机在SnapCenter服务器上注册插件。添加主机时，选择“无”作为凭证。添加主机后，会自动发现已安装的插件。



== 静默模式下安装 AIX 插件包

您可以使用命令行界面 (CLI) 以静默模式安装适用于 AIX 的SnapCenter插件包。

*您需要什么*

* 您应该查看安装插件包的先决条件。
* 您应该确保未设置 DISPLAY 环境变量。
+
如果设置了 DISPLAY 环境变量，则应运行 unset DISPLAY，然后尝试手动安装插件。



*步骤*

. 从SnapCenter服务器安装位置下载适用于 AIX 的SnapCenter插件包。
+
默认安装路径为_C:\ProgramData\ NetApp\ SnapCenter\PackageRepository_。可以从安装SnapCenter服务器的主机访问此路径。

. 从命令提示符处，导航到下载安装文件的目录。
. 运行
+
`./snapcenter_aix_host_plugin.bsx-i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path-DINSTALL_LOG_NAME=SnapCenter_AIX_Host_Plug-in_Install_MANUAL.log-DCHOSEN_FEATURE_LIST=CUSTOMDSPL_USER=install_user`

. 编辑位于 _/var/opt/snapcenter/spl/etc/_ 的 spl.properties 文件以添加 SPL_ENABLED_PLUGINS=SCO,SCU，然后重新启动SnapCenter插件Loader服务。



IMPORTANT: 插件包的安装会在主机上注册插件，而不是在SnapCenter服务器上注册。您应该通过使用SnapCenter GUI 或 PowerShell cmdlet 添加主机在SnapCenter服务器上注册插件。添加主机时，选择“无”作为凭证。添加主机后，会自动发现已安装的插件。
