---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter如何发现 Oracle 数据库。 
---
= RAC 设置中的首选节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 Oracle Real Application Clusters (RAC) 设置中，您可以指定SnapCenter用于执行备份操作的首选节点。如果您未指定首选节点， SnapCenter会自动分配一个节点作为首选节点，并在该节点上创建备份。

首选节点可能是 RAC 数据库实例所在的集群节点之一或所有集群节点。备份操作仅在这些优先节点上按照优先顺序触发。

.示例
RAC 数据库 cdbrac 有三个实例：节点 1 上的 cdbrac1、节点 2 上的 cdbrac2 和节点 3 上的 cdbrac3。

node1 和 node2 实例被配置为首选节点，其中 node2 为第一首选，node1 为第二首选。执行备份操作时，首先在 node2 上尝试执行该操作，因为它是第一个首选节点。

如果 node2 未处于备份状态，这可能是由于多种原因造成的，例如插件代理未在主机上运行、主机上的数据库实例未处于指定备份类型所需的状态，或者 FlexASM 配置中 node2 上的数据库实例未由本地 ASM 实例提供服务；然后将在 node1 上尝试执行该操作。

由于 node3 不在首选节点列表中，因此不会用于备份。



== Flex ASM 设置

在 Flex ASM 设置中，如果基数小于 RAC 集群中的节点数，则叶节点将不会被列为首选节点。如果 Flex ASM 集群节点角色有任何变化，您应该手动发现以便刷新首选节点。



== 所需的数据库状态

首选节点上的 RAC 数据库实例必须处于所需状态才能成功完成备份：

* 配置的首选节点中的一个 RAC 数据库实例必须处于打开状态才能创建在线备份。
* 配置的首选节点中的一个 RAC 数据库实例必须处于挂载状态，并且所有其他实例（包括其他首选节点）必须处于挂载状态或更低状态才能创建脱机挂载备份。
* RAC 数据库实例可以处于任何状态，但必须指定首选节点来创建离线关闭备份。

