---
permalink: protect-sco/reference_requirements_for_restoring_an_oracle_database.html 
sidebar: sidebar 
keywords:  
summary: 在恢复 Oracle 数据库之前，您应该确保先决条件已满足。 
---
= 恢复 Oracle 数据库的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在恢复 Oracle 数据库之前，您应该确保先决条件已满足。

* 您应该已经定义了您的恢复和恢复策略。
* 如果您要将快照复制到镜像或保管库， SnapCenter管理员应该已经为源卷和目标卷分配了存储虚拟机 (SVM)。
* 如果存档日志作为备份的一部分被修剪，则您应该手动安装所需的存档日志备份。
* 如果要恢复驻留在虚拟机磁盘 (VMDK) 上的 Oracle 数据库，则应确保客户机具有所需数量的可用插槽来分配克隆的 VMDK。
* 如果为该数据库启用了二级保护，则应确保属于该数据库的所有数据卷和存档日志卷都受到保护。
* 您应该确保 RAC One Node 数据库处于“nomount”状态以执行控制文件或完整数据库还原。
* 如果您在 NFS 环境中有一个 ASM 数据库实例，则应将 ASM 磁盘路径 _/var/opt/snapcenter/scu/clones/*/*_ 添加到 asm_diskstring 参数中定义的现有路径，以便成功挂载 ASM 日志备份作为恢复操作的一部分。
* 在 asm_diskstring 参数中，如果使用 ASMFD，则应配置 _AFD:*_；如果使用 ASMLIB，则应配置 _ORCL:*_。
+

NOTE: 有关如何编辑 asm_diskstring 参数的信息，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter["如何将磁盘路径添加到 asm_diskstring"^]

* 如果您已禁用 OS 身份验证并启用 Oracle 数据库身份验证，并且想要恢复该数据库的数据文件和控制文件，则应在 *listener.ora* 文件中配置静态侦听器，对于非 ASM 数据库，该文件位于 _$ORACLE_HOME/network/admin_，对于 ASM 数据库，该文件位于 _$GRID_HOME/network/admin_，并且想要恢复该数据库的数据文件和控制文件。
* 如果数据库大小以 TB 为单位，则应通过运行 Set-SmConfigSettings 命令来增加 SCORestoreTimeout 参数的值。
* 您应该确保 vCenter 所需的所有许可证都已安装并且是最新的。
+
如果许可证未安装或不是最新的，则会显示警告消息。如果您忽略警告并继续，从 RDM 恢复将失败。

* 您应该确保 LUN 没有使用由混合协议 iSCSI 和 FC 组成的 iGroup 映射到 AIX 主机。有关更多信息，请参阅 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_Plug-in_for_Oracle_operations_fail_with_error_Unable_to_discover_the_device_for_LUN_LUN_PATH["操作失败，错误：无法发现 LUN 的设备"^] 。

