---
permalink: protect-sco/reference_requirements_for_cloning_an_oracle_database.html 
sidebar: sidebar 
keywords:  
summary: 在克隆 Oracle 数据库之前，您应该确保先决条件已完成。 
---
= 克隆 Oracle 数据库的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在克隆 Oracle 数据库之前，您应该确保先决条件已完成。

* 您应该已经使用SnapCenter创建了数据库的备份。
+
您应该已经成功创建了在线数据和日志备份或离线（安装或关闭）备份，克隆操作才能成功。

* 如果要自定义控制文件或重做日志文件路径，则应该预先配置所需的文件系统或自动存储管理 (ASM) 磁盘组。
+
默认情况下，会在 SnapCenter 为克隆数据库的数据文件配置的 ASM 磁盘组或文件系统上创建克隆数据库的重做日志和控制文件。

* 如果您使用 NFS 上的 ASM，则应将 _/var/opt/snapcenter/scu/clones/*/*_ 添加到 asm_diskstring 参数中定义的现有路径。
* 在 asm_diskstring 参数中，如果使用 ASMFD，则应配置 _AFD:*_；如果使用 ASMLIB，则应配置 _ORCL:*_。
+
有关如何编辑 asm_diskstring 参数的信息，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter["如何将磁盘路径添加到 asm_diskstring"^]。

* 如果要在备用主机上创建克隆，则备用主机应满足以下要求：
+
** 应在备用主机上安装适用于 Oracle 数据库的SnapCenter插件。
** 克隆主机应该能够从主存储或辅助存储中发现 LUN。
+
*** 如果您要从主存储或辅助（Vault 或镜像）存储克隆到备用主机，请确保在辅助存储和备用主机之间建立 iSCSI 会话，或者针对 FC 正确划分区域。
*** 如果要从 Vault 或镜像存储克隆到同一主机，请确保在 Vault 或镜像存储与主机之间建立 iSCSI 会话，或者针对 FC 正确划分区域。
*** 如果在虚拟化环境中进行克隆，请确保在主存储或辅助存储与托管备用主机的 ESX 服务器之间建立 iSCSI 会话，或者针对 FC 进行正确分区。
+
有关信息，请参阅 https://docs.netapp.com/us-en/ontap-sanhost/["主机实用程序文档"]。



** 如果源数据库是 ASM 数据库：
+
*** ASM 实例应该在将执行克隆的主机上启动并运行。
*** 如果要将克隆数据库的存档日志文件放置在专用 ASM 磁盘组中，则应在克隆操作之前配置 ASM 磁盘组。
*** 可以配置数据磁盘组的名称，但请确保该名称未被执行克隆的主机上的任何其他 ASM 磁盘组使用。
+
驻留在 ASM 磁盘组上的数据文件作为SnapCenter克隆工作流的一部分进行配置。



** 对于 NVMe，应安装 NVMe util


* 数据 LUN 和日志 LUN 的保护类型（例如镜像、保管库或镜像保管库）应该相同，以便在使用日志备份克隆到备用主机期间发现辅助定位器。
* 您应该在源数据库参数文件中将 exclude_seed_cdb_view 的值设置为 FALSE，以检索用于克隆 12_c_ 数据库备份的种子 PDB 相关信息。
+
种子 PDB 是系统提供的模板，CDB 可以使用它来创建 PDB。种子 PDB 名为 PDB$SEED。有关 PDB$SEED 的信息，请参阅 Oracle Doc ID 1940806.1。

+

NOTE: 您应该在备份 12_c_ 数据库之前设置该值。

* SnapCenter支持由 autofs 子系统管理的文件系统的备份。如果要克隆数据库，请确保数据挂载点不在 autofs 挂载点的根目录下，因为插件主机的根用户没有权限在 autofs 挂载点的根目录下创建目录。
+
如果控制和重做日志文件位于数据挂载点下，则应修改控制文件路径，然后相应地修改重做日志文件路径。

+

NOTE: 您可以手动向 autofs 子系统注册新的克隆挂载点。新克隆的挂载点不会自动注册。

* 如果您有 TDE（自动登录）并希望在同一台或备用主机上克隆数据库，则应将 _/etc/ORACLE/WALLET/$ORACLE_SID_ 下的钱包（密钥文件）从源数据库复制到克隆的数据库。
* 您应该在 _/etc/lvm/lvm.conf_ 中设置 use_lvmetad = 0 的值并停止 lvm2-lvmetad 服务，以便在 Oracle Linux 7 或更高版本或 Red Hat Enterprise Linux (RHEL) 7 或更高版本上的存储区域网络 (SAN) 环境中成功执行克隆。
* 如果您使用的是 Oracle 数据库 11.2.0.3 或更高版本，并且使用 NID 脚本更改了辅助实例的数据库 ID，则应安装 13366202 Oracle 补丁。
* 您应确保托管卷的聚合位于存储虚拟机 (SVM) 的已分配聚合列表中。
* 对于 NVMe，如果必须排除任何目标端口的连接，则应在 /var/opt/snapcenter/scu/etc/nvme.conf 文件中添加目标节点名称和端口名称。
+
如果该文件不存在，您应该按照以下示例所示创建该文件：

+
....
blacklist {
nn-0x<target_node_name_1>:pn-0x<target_port_name_1>
nn-0x<target_node_name_2>:pn-0x<target_port_name_2>
}
....
* 您应该确保 LUN 没有使用由混合协议 iSCSI 和 FC 组成的 iGroup 映射到 AIX 主机。有关更多信息，请参阅 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_Plug-in_for_Oracle_operations_fail_with_error_Unable_to_discover_the_device_for_LUN_LUN_PATH["操作失败，错误：无法发现 LUN 的设备"^] 。

