---
permalink: protect-sce/reference_storage_types_supported_by_snapcenter_plug_in_for_microsoft_windows_and_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server 
summary: SnapCenter支持物理机和虚拟机上的多种存储类型。在为您的主机安装软件包之前，您必须验证您的存储类型是否受支持。 
---
= SnapCenter插件（适用于 Microsoft Windows 和 Microsoft Exchange Server）支持的存储类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter支持物理机和虚拟机上的多种存储类型。在为您的主机安装软件包之前，您必须验证您的存储类型是否受支持。

Windows Server 上提供SnapCenter配置和数据保护支持。有关受支持版本的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=121031;&solution=1259&isHWU&src=IMT[][NetApp互操作性矩阵工具^]。

|===
| 机器 | 存储类型 | 使用配置 | 支持说明 


 a| 
物理服务器
 a| 
FC 连接的 LUN
 a| 
SnapCenter图形用户界面 (GUI) 或 PowerShell cmdlet
 a| 



 a| 
物理服务器
 a| 
iSCSI 连接的 LUN
 a| 
SnapCenter GUI 或 PowerShell cmdlet
 a| 



 a| 
VMware VM
 a| 
通过 FC 或 iSCSI HBA 连接的 RDM LUN
 a| 
PowerShell cmdlet
 a| 
仅物理兼容性


NOTE: 不支持 VMDK。



 a| 
VMware VM
 a| 
iSCSI LUN 由 iSCSI 启动器直接连接到客户系统
 a| 
SnapCenter GUI 或 PowerShell cmdlet
 a| 

NOTE: 不支持 VMDK。



 a| 
Hyper-V 虚拟机
 a| 
通过虚拟光纤通道交换机连接的虚拟 FC (vFC) LUN
 a| 
SnapCenter GUI 或 PowerShell cmdlet
 a| 
您必须使用 Hyper-V 管理器来配置由虚拟光纤通道交换机连接的虚拟 FC (vFC) LUN。


NOTE: 不支持 Hyper-V 直通磁盘和在NetApp存储上配置的 VHD(x) 上的备份数据库。



 a| 
Hyper-V 虚拟机
 a| 
iSCSI LUN 由 iSCSI 启动器直接连接到客户系统
 a| 
SnapCenter GUI 或 PowerShell cmdlet
 a| 

NOTE: 不支持 Hyper-V 直通磁盘和在NetApp存储上配置的 VHD(x) 上的备份数据库。

|===