---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: '在创建备份作业之前定义备份策略有助于确保您拥有成功还原数据库所需的备份。您的服务水平协议 (SLA)、恢复时间目标 (RTO) 和恢复点目标 (RPO) 在很大程度上决定了您的备份策略。' 
---
= 定义 Exchange Server 资源的备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建备份作业之前定义备份策略有助于确保您拥有成功还原数据库所需的备份。您的服务水平协议 (SLA)、恢复时间目标 (RTO) 和恢复点目标 (RPO) 在很大程度上决定了您的备份策略。

SLA 定义了预期的服务级别并解决了许多与服务相关的问题，包括服务的可用性和性能。  RTO 是指服务中断后必须恢复业务流程的时间。  RPO 定义了必须从备份存储中恢复的文件的年龄策略，以便在故障后恢复常规操作。  SLA、RTO 和 RPO 有助于备份策略。



== Exchange 数据库支持的备份类型

使用SnapCenter备份 Exchange 邮箱需要您选择资源类型，例如数据库和数据库可用性组 (DAG)。利用快照技术来创建资源所在卷的在线、只读副本。

|===
| 备份类型 | 描述 


 a| 
完整备份和日志备份
 a| 
备份数据库和所有事务日志，包括截断的日志。

完整备份完成后，Exchange Server 会截断已提交到数据库的事务日志。

通常，您应该选择此选项。但是，如果您的备份时间很短，您可以选择不运行事务日志备份，而是进行完整备份。



 a| 
完整备份
 a| 
备份数据库和事务日志。

截断的事务日志不会被备份。



 a| 
日志备份
 a| 
备份所有事务日志。

已提交到数据库的截断日志不会被备份。如果您在完整数据库备份之间安排频繁的事务日志备份，则可以选择粒度恢复点。

|===


== 数据库插件的备份计划

备份频率（计划类型）在策略中指定；备份计划在资源组配置中指定。确定备份频率或计划的最关键因素是资源的变化率和数据的重要性。您可能每小时备份一次使用频繁的资源，而可能每天备份一次很少使用的资源。其他因素包括资源对您的组织的重要性、您的服务水平协议 (SLA) 和您的恢复点目标 (RPO)。

SLA 定义了预期的服务级别并解决了许多与服务相关的问题，包括服务的可用性和性能。  RPO 定义了必须从备份存储中恢复的文件的年龄策略，以便在故障后恢复常规操作。  SLA 和 RPO 有助于数据保护策略。

即使对于使用频繁的资源，也不需要每天运行一次或两次以上的完整备份。例如，定期的事务日志备份可能足以确保您拥有所需的备份。备份数据库的频率越高， SnapCenter在恢复时需要使用的事务日志就越少，从而可以加快恢复操作的速度。

备份计划分为两部分，如下所示：

* 备份频率
+
备份频率（执行备份的频率），对于某些插件来说称为_计划类型_，是策略配置的一部分。您可以选择每小时、每天、每周或每月作为策略的备份频率。如果您未选择任何频率，则创建的策略是仅按需策略。您可以通过单击“*设置*”>“*策略*”来访问策略。

* 备份计划
+
备份计划（确切地指定执行备份的时间）是资源组配置的一部分。例如，如果您有一个资源组，该资源组的策略配置为每周备份，则可以将计划配置为每周四晚上 10:00 进行备份。您可以通过单击“*资源*”>“*资源组*”来访问资源组计划。





== 数据库所需的备份作业数量

决定所需备份作业数量的因素包括资源的大小、使用的卷数、资源的变化率以及服务水平协议 (SLA)。



== 备份命名约定

您可以使用默认快照命名约定，也可以使用自定义命名约定。默认备份命名约定会在快照名称中添加时间戳，以帮助您识别副本的创建时间。

快照使用以下默认命名约定：

`resourcegroupname_hostname_timestamp`

您应该对备份资源组进行逻辑命名，如下例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在这个例子中，语法元素具有以下含义：

* _dts1_ 是资源组名称。
* _mach1x88_ 是主机名。
* _03-12-2015_23.17.26_ 是日期和时间戳。


或者，您可以在保护资源或资源组时通过选择“使用自定义名称格式进行 Snapshot 复制”来指定 Snapshot 名称格式。例如，customtext_resourcegroup_policy_hostname 或 resourcegroup_hostname。默认情况下，时间戳后缀会添加到快照名称中。



== 备份保留选项

您可以选择保留备份副本的天数，或者指定要保留的备份副本数量， ONTAP最多可保留 255 份。例如，您的组织可能要求您保留 10 天的备份副本或 130 份备份副本。

创建策略时，您可以指定备份类型和计划类型的保留选项。

如果您设置了SnapMirror复制，则保留策略将在目标卷上镜像。

SnapCenter会删除具有与计划类型匹配的保留标签的保留备份。如果资源或资源组的计划类型发生更改，则具有旧计划类型标签的备份可能仍保留在系统中。


NOTE: 为了长期保留备份副本，您应该使用SnapVault备份。



== 在 Exchange Server 的源存储卷上保留事务日志备份的时间

适用于 Microsoft Exchange Server 的SnapCenter插件需要事务日志备份来执行最新的还原操作，该操作将数据库还原到两次完整备份之间的时间。

例如，如果 Plug-in for Exchange 在上午 8:00 进行了一次完整备份和事务日志备份，并在下午 5:00 进行了另一次完整备份和事务日志备份，则它可以使用最新的事务日志备份将数据库还原到上午 8:00 至下午 5:00 之间的任何时间。如果没有事务日志，Plug-in for Exchange 只能执行时间点还原操作，即将数据库还原到 Plug-in for Exchange 完成完整备份的时间。

通常，您只需要一两天的最新恢复操作。默认情况下， SnapCenter至少保留两天。
