---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 您可以在使用SnapCenter备份 Microsoft Exchange Server 资源之前为 Exchange 资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。 
---
= 为 Exchange Server 数据库创建备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用SnapCenter备份 Microsoft Exchange Server 资源之前为 Exchange 资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。

.开始之前
* 您必须已经定义了您的数据保护策略。
+
有关详细信息，请参阅有关定义 Exchange 数据库的数据保护策略的信息。

* 您必须通过完成安装SnapCenter、添加主机、识别资源和创建存储系统连接等任务来为数据保护做好准备。
* 您必须刷新（发现）Exchange Server 资源。
* 如果您要将快照复制到镜像或保管库， SnapCenter管理员必须已为您分配源卷和目标卷的存储虚拟机 (SVM)。
* 如果要在前言和后言中运行 PowerShell 脚本，则应设置 `usePowershellProcessforScripts`参数为 true `web.config`文件。
+
默认值为 false。

* 查看SnapMirror主动同步特定的先决条件和限制。欲了解详细信息，请参阅 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror主动同步的对象限制"]。


.关于此任务
* 备份策略是一组规则，用于控制如何管理和保留备份以及资源或资源组的备份频率。此外，您还可以指定脚本设置。当您想要将策略重新用于另一个资源组时，在策略中指定选项可以节省时间。
* 完整备份保留特定于给定的策略。使用策略 A 且完整备份保留期为 4 的数据库或资源将保留 4 个完整备份，并且对同一数据库或资源的策略 B 没有影响，策略 B 可能具有保留期为 3 以保留 3 个完整备份。
* 日志备份保留跨策略有效，并适用于数据库或资源的所有日志备份。因此，当使用策略 B 执行完整备份时，日志保留设置会影响策略 A 在同一数据库或资源上创建的日志备份。同样，策略 A 的日志保留设置会影响策略 B 在同一数据库上创建的日志备份。
* SCRIPTS_PATH 是使用插件主机的 SMCoreServiceHost.exe.Config 文件中的 PredefinedWindowsScriptsDirectory 键定义的。
+
如果需要，您可以更改此路径并重新启动 SMcore 服务。为了安全起见，建议您使用默认路径。

+
可以通过 API 从 Swagger 显示该键的值：API /4.7/configsettings

+
您可以使用 GET API 来显示键的值。不支持 SET API。

+
|===


| *最佳实践：*最好根据您想要保留的完整备份和日志备份的总数来配置辅助保留策略。配置辅助保留策略时，请记住，当数据库和日志位于不同的卷时，每个备份可以有三个快照，而当数据库和日志位于同一卷时，每个备份可以有两个快照。 
|===
* SnapLock
+
** 如果选择了“保留备份副本特定天数”选项，则SnapLock保留期必须小于或等于上述保留天数。
+
指定快照锁定期可防止在保留期到期之前删除快照。这可能导致保留的快照数量超过策略中指定的数量。

+
对于ONTAP 9.12.1 及以下版本、从SnapLock Vault 快照创建的克隆将继承SnapLock Vault 到期时间。存储管理员应在SnapLock到期后手动清理克隆。





.步骤
. 在左侧导航窗格中，单击“*设置*”。
. 在“设置”页面中，单击“*策略*”。
. 单击“*新建*”。
. 在名称页面中，输入策略名称和详细信息。
. 在备份类型和复制页面中，执行以下步骤：
+
.. 选择备份类型：
+
|===
| 目的 | 操作 


 a| 
备份数据库文件和所需的事务日志
 a| 
选择*完整备份和日志备份*。

数据库采用日志截断备份，备份所有日志，包括被截断的日志。


NOTE: 这是推荐的备份类型。



 a| 
备份数据库文件和未提交的事务日志
 a| 
选择*完整备份*。

数据库备份时会进行日志截断，截断的日志不会备份。



 a| 
备份所有事务日志
 a| 
选择*日志备份*。

活动文件系统上的所有事务日志都已备份，并且没有日志截断。

在与实时日志相同的磁盘上创建 _scebackupinfo_ 目录。该目录包含指向 Exchange 数据库增量更改的指针，它并不等同于完整的日志文件。



 a| 
备份所有数据库文件和事务日志，而不截断事务日志文件
 a| 
选择*复制备份*。

所有数据库和所有日志均已备份，并且没有日志截断。您通常使用此备份类型来重新播种副本或测试或诊断问题。

|===
+

NOTE: 您应该根据完整备份保留而不是最新 (UTM) 保留来定义日志备份所需的空间。

+

NOTE: 处理 Exchange 卷 (LUN) 时，为日志和数据库创建单独的保管库策略，并使用相同的标签将日志策略的保留 (keep) 设置为数据库策略的每个标签数量的两倍。欲了解更多信息，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["SnapCenter for Exchange 备份仅保留 Vault 目标日志卷上的一半快照"^]

.. 在数据库可用性组设置部分中，选择一个操作：
+
|===
| 对于这个领域... | 操作 


 a| 
备份活动副本
 a| 
选择此选项可仅备份所选数据库的活动副本。

对于数据库可用性组 (DAG)，此选项仅备份 DAG 中所有数据库的活动副本。

被动副本未备份。



 a| 
在创建备份作业时选择的服务器上备份副本
 a| 
选择此选项可备份选定服务器（主动服务器和被动服务器）上数据库的任何副本。

对于 DAG，此选项将备份选定服务器上所有数据库的主动副本和被动副本。

|===
+

NOTE: 在集群配置中，备份根据策略中设置的保留设置保留在集群的每个节点上。如果集群的所有者节点发生变化，则会保留前一个所有者节点的备份。保留仅适用于节点级别。

.. 在“计划频率”部分中，选择一种或多种频率类型：*按需*、*每小时*、*每天*、*每周*和*每月*。
+

NOTE: 您可以在创建资源组时指定备份操作的计划（开始日期、结束日期）。这使您能够创建共享相同策略和备份频率的资源组，但允许您为每个策略分配不同的备份计划。

+

NOTE: 如果您已安排在凌晨 2:00，则夏令时 (DST) 期间不会触发该计划。

.. 选择策略标签。
+

NOTE: 您可以为远程复制的主快照分配SnapMirror标签，从而允许主快照将快照复制操作从SnapCenter卸载到ONTAP二级系统。无需在策略页面中启用SnapMirror或SnapVault选项即可完成此操作。

.. 在“选择辅助复制选项”部分中，选择以下一个或两个辅助复制选项：
+
|===
| 对于这个领域... | 操作 


 a| 
创建本地快照后更新SnapMirror
 a| 
选择此选项可在另一个卷上保留备份集的镜像副本（SnapMirror）。

在二次复制期间， SnapLock到期时间会加载主SnapLock到期时间。

应为SnapMirror主动同步启用此选项。


IMPORTANT: 如果为 Exchange ONTAP卷设置了SnapMirror主动同步，则无法使用仅主策略。 SnapCenter不允许这样做。您应该启用“镜像”选项。

单击拓扑页面中的“*刷新*”按钮可刷新从ONTAP检索到的辅助和主SnapLock到期时间。

看link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["在拓扑页面中查看 Exchange 备份"] 。



 a| 
创建本地快照后更新SnapVault
 a| 
选择此选项可执行磁盘到磁盘的备份复制。



 a| 
错误重试次数
 a| 
输入进程停止之前应发生的复制尝试次数。

|===
+

NOTE: 您应该在ONTAP中为二级存储配置SnapMirror保留策略，以避免达到二级存储上快照的最大限制。



. 在保留页面中，配置保留设置。
+
显示的选项取决于您之前选择的备份类型和频率类型。

+

NOTE: 最大保留值为 1018。如果保留设置的值高于底层ONTAP版本支持的值，则备份将失败。

+

IMPORTANT: 如果您计划启用SnapVault复制，则必须将保留计数设置为 2 或更高。如果将保留计数设置为 1，则保留操作可能会失败，因为第一个快照是SnapVault关系的参考快照，直到较新的快照复制到目标。

+
.. 在“日志备份保留设置”部分中，选择下列选项之一：
+
|===
| 目的 | 操作 


 a| 
仅保留特定数量的日志备份
 a| 
选择*保留日志的完整备份数*，并指定您想要最新恢复的完整备份数。

最新 (UTM) 保留适用于通过完整或日志备份创建的日志备份。例如，如果将 UTM 保留设置配置为保留最近 5 次完整备份的日志备份，则会保留最近 5 次完整备份的日志备份。

作为完整和日志备份的一部分创建的日志文件夹将作为 UTM 的一部分自动删除。您不能手动删除日志文件夹。例如，如果完整或完整和日志备份的保留设置设为 1 个月，而 UTM 保留设置为 10 天，则作为这些备份的一部分创建的日志文件夹将根据 UTM 删除。因此，只有 10 天的日志文件夹会存在，所有其他备份都标记为时间点恢复。

如果您不想执行最新恢复，可以将 UTM 保留值设置为 0。这将启用时间点恢复操作。

*最佳实践：*最好该设置必须等于完整备份保留设置部分中的总快照（完整备份）的设置。这可确保每次完整备份时都保留日志文件。



 a| 
将备份副本保留特定天数
 a| 
选择“保留最后的日志备份”选项，并指定保留日志备份副本的天数。

日志备份最多保留完整备份的天数。



 a| 
快照锁定期
 a| 
选择*Snapshot 副本锁定期限*，并选择天、月或年。

SnapLock保留期应少于 100 年。

|===
+
如果您选择“*日志备份*”作为备份类型，则日志备份将作为完整备份的最新保留设置的一部分保留。

.. 在完整备份保留设置部分中，为按需备份选择以下选项之一，然后为完整备份选择一项：
+
|===
| 对于这个领域... | 操作 


 a| 
仅保留特定数量的快照
 a| 
如果要指定要保留的完整备份数量，请选择*要保留的 Snapshot 副本总数*选项，并指定要保留的快照（完整备份）数量。

如果完整备份的数量超过指定数量，则会删除超过指定数量的完整备份，并首先删除最旧的副本。



 a| 
保留完整备份特定天数
 a| 
选择“保留快照副本”选项，并指定保留快照（完整备份）的天数。



 a| 
主快照锁定期
 a| 
选择*主快照副本锁定期限*，并选择天、月或年。

SnapLock保留期应少于 100 年。



 a| 
二级快照锁定期
 a| 
选择*次快照副本锁定期限*，并选择天、月或年。

|===
+
如果 DAG 配置中的主机上有一个仅具有日志备份而没有完整备份的数据库，则日志备份将通过以下方式保留：

+
*** 默认情况下， SnapCenter会在 DAG 中的所有其他主机中查找此数据库的最早完整备份，并删除在完整备份之前在此主机上进行的所有日志备份。
*** 您可以通过在 _C:\Program Files\ NetApp\ SnapCenter WebApp\web.config_ 文件中添加键 *MaxLogBackupOnlyCountWithoutFullBackup* 来覆盖仅具有日志备份的 DAG 中主机上的数据库的上述默认保留行为。
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
在示例中，值 10 表示您在主机上保留最多 10 个日志备份。





. 在脚本页面中，分别输入应在备份操作之前或之后运行的前置脚本或后置脚本的路径和参数。
+
** 预设备份参数包括“$Database”和“$ServerInstance”。
** Postscript 备份参数包括“$Database”、“$ServerInstance”、“$BackupName”、“$LogDirectory”和“$LogSnapshot”。
+
您可以运行脚本来更新 SNMP 陷阱、自动发出警报、发送日志等。

+

NOTE: 前言或后记路径不应包含驱动器或共享。该路径应相对于 SCRIPTS_PATH。



. 查看摘要，然后单击“*完成*”。

