---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: 在安装适用于 Windows 的插件之前，您应该了解某些安装要求。 
---
= 适用于 Microsoft Windows 的SnapCenter插件的安装要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装适用于 Windows 的插件之前，您应该了解某些安装要求。

在开始使用适用于 Windows 的插件之前， SnapCenter管理员必须安装和配置SnapCenter服务器并执行先决条件任务。

* 您必须具有SnapCenter管理员权限才能安装适用于 Windows 的插件。
+
SnapCenter管理员角色必须具有管理员权限。

* 您必须已安装并配置SnapCenter服务器。
* 在 Windows 主机上安装插件时，如果指定非内置的凭据或用户属于本地工作组用户，则必须在主机上禁用 UAC。
* 如果您想要备份复制，则必须设置SnapMirror和SnapVault 。




== 安装适用于 Windows 的SnapCenter插件包的主机要求

在安装适用于 Windows 的SnapCenter插件包之前，您应该熟悉一些基本的主机系统空间要求和大小要求。

|===
| 物品 | 要求 


 a| 
操作系统
 a| 
Microsoft Windows

有关受支持版本的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 互操作性表工具"^]。

如果您使用的是 Windows 集群设置，您还应该安装和配置 Windows 远程管理 (WinRM)。



 a| 
主机上SnapCenter插件的最小 RAM
 a| 
1 GB



 a| 
主机上SnapCenter插件的最小安装和日志空间
 a| 
5 GB


NOTE: 您应该分配足够的磁盘空间并监控日志文件夹的存储消耗。所需的日志空间取决于要保护的实体的数量和数据保护操作的频率。如果没有足够的磁盘空间，则不会为最近运行的操作创建日志。



 a| 
所需的软件包
 a| 
* ASP.NET Core Runtime 8.0.12（以及所有后续 8.0.x 补丁）托管包
* PowerShell 核心 7.4.2


有关受支持版本的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 互操作性表工具"^]。

有关 .NET 特定的故障排除信息，请参阅 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["对于没有互联网连接的传统系统， SnapCenter升级或安装将失败。"]

|===


== 设置 Windows 插件的凭据

SnapCenter使用凭据对SnapCenter操作的用户进行身份验证。您应该创建用于安装SnapCenter插件的凭据，以及用于在 Windows 文件系统上执行数据保护操作的附加凭据。

*您需要什么*

* 在安装插件之前，您必须设置 Windows 凭据。
* 您必须在远程主机上设置具有管理员权限（包括管理员权利）的凭据。
* 如果您为单个资源组设置了凭据，并且用户没有完全管理权限，则必须至少为该用户分配资源组和备份权限。


*步骤*

. 在左侧导航窗格中，单击“*设置*”。
. 在“设置”页面中，单击“*凭据*”。
. 单击“*新建*”。
. 在“凭据”页面中，执行以下操作：
+
|===
| 对于这个领域... | 操作 


 a| 
凭证名称
 a| 
输入凭证的名称。



 a| 
用户名/密码
 a| 
输入用于身份验证的用户名和密码。

** 域管理员或管理员组的任何成员
+
指定要安装SnapCenter插件的系统上的域管理员或管理员组的任何成员。用户名字段的有效格式如下：

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`
*** `UserName@upn`


** 本地管理员（仅适用于工作组）
+
对于属于工作组的系统，请在要安装SnapCenter插件的系统上指定内置的本地管理员。如果用户帐户具有提升的权限或主机系统上禁用了用户访问控制功能，则可以指定属于本地管理员组的本地用户帐户。用户名字段的有效格式如下： `UserName`

+
请勿在密码中使用双引号（“）或反引号（`）。密码中不应同时使用小于号 (<) 和感叹号 (!) 符号。例如，lessthan<!10、lessthan10<!、backtick`12。





 a| 
密码
 a| 
输入用于身份验证的密码。

|===
. 单击“*确定*”。
+
完成凭据设置后，您可能希望在“用户和访问”页面上将凭据维护分配给用户或用户组。





== 在 Windows Server 2016 或更高版本上配置 gMSA

Windows Server 2016 或更高版本允许您创建组托管服务帐户 (gMSA)，该帐户从托管域帐户提供自动服务帐户密码管理。

.开始之前
* 您应该拥有 Windows Server 2016 或更高版本的域控制器。
* 您应该拥有一个 Windows Server 2016 或更高版本的主机，它是域的成员。


.步骤
. 创建 KDS 根密钥来为 gMSA 中的每个对象生成唯一的密码。
. 对于每个域，从 Windows 域控制器运行以下命令：Add-KDSRootKey -EffectiveImmediately
. 创建并配置 gMSA：
+
.. 创建用户组账号，格式如下：
+
 domainName\accountName$
.. 将计算机对象添加到组中。
.. 使用您刚刚创建的用户组来创建 gMSA。
+
例如，

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. 跑步 `Get-ADServiceAccount`命令来验证服务帐户。


. 在您的主机上配置 gMSA：
+
.. 在要使用 gMSA 帐户的主机上启用 Windows PowerShell 的 Active Directory 模块。
+
为此，请从 PowerShell 运行以下命令：

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. 重新启动主机。
.. 通过从 PowerShell 命令提示符运行以下命令在主机上安装 gMSA： `Install-AdServiceAccount <gMSA>`
.. 通过运行以下命令验证你的 gMSA 帐户： `Test-AdServiceAccount <gMSA>`


. 将管理权限分配给主机上配置的 gMSA。
. 通过在SnapCenter服务器中指定配置的 gMSA 帐户来添加 Windows 主机。
+
SnapCenter Server 将在主机上安装选定的插件，并且指定的 gMSA 将在插件安装期间用作服务登录帐户。


