---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: '在创建备份之前定义备份策略可为您提供成功恢复或克隆文件系统所需的备份。您的服务级别协议 (SLA)、恢复时间目标 (RTO) 和恢复点目标 (RPO) 在很大程度上决定了您的备份策略。' 
---
= 定义 Windows 文件系统的备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建备份之前定义备份策略可为您提供成功恢复或克隆文件系统所需的备份。您的服务级别协议 (SLA)、恢复时间目标 (RTO) 和恢复点目标 (RPO) 在很大程度上决定了您的备份策略。

SLA 定义了预期的服务级别并解决了许多与服务相关的问题，包括服务的可用性和性能。  RTO 是服务中断后必须恢复业务流程的时间。  RPO 定义了必须从备份存储中恢复的文件的年龄策略，以便在故障后恢复常规操作。  SLA、RTO 和 RPO 有助于数据保护策略。



== Windows 文件系统的备份计划

备份频率在策略中指定；备份计划在资源组配置中指定。确定备份频率或计划的最关键因素是资源的变化率和数据的重要性。您可能每小时备份一次使用频繁的资源，而可能每天备份一次很少使用的资源。其他因素包括资源对您的组织的重要性、您的服务水平协议 (SLA) 和您的恢复点目标 (RPO)。

SLA 定义了预期的服务级别并解决了许多与服务相关的问题，包括服务的可用性和性能。  RPO 定义了必须从备份存储中恢复的文件的年龄策略，以便在故障后恢复常规操作。  SLA 和 RPO 有助于数据保护策略。

即使对于使用频繁的资源，也不需要每天运行一次或两次以上的完整备份。

备份计划分为两部分，如下所示：

* 备份频率
+
备份频率（执行备份的频率），对于某些插件来说称为_计划类型_，是策略配置的一部分。例如，您可以将备份频率配置为每小时、每天、每周或每月，或者您可以指定 *None*，这使该策略成为仅按需策略。您可以通过单击“*设置*”>“*策略*”来访问策略。

* 备份计划
+
备份计划（确切地指定执行备份的时间）是资源组配置的一部分。例如，如果您有一个资源组，该资源组的策略配置为每周备份，则可以将计划配置为每周四晚上 10:00 进行备份。您可以通过单击“*资源*”>“*资源组*”来访问资源组计划。





== Windows 文件系统所需的备份数量

决定所需备份数量的因素包括 Windows 文件系统的大小、使用的卷数、文件系统的变化率以及您的服务级别协议 (SLA)。



== Windows 文件系统的备份命名约定

Windows 文件系统备份使用默认的快照命名约定。默认备份命名约定会在快照名称中添加时间戳，以帮助您识别副本的创建时间。

快照使用以下默认命名约定：resourcegroupname_hostname_timestamp

您应该对备份资源组进行逻辑命名，如下例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在这个例子中，语法元素具有以下含义：

* `dts1`是资源组名称。
* `mach1x88`是主机名。
* `03-12-2016_23.17.26`是日期和时间戳。


创建备份时，您还可以添加描述性标签来帮助识别备份。相反，如果您想使用自定义的备份命名约定，则需要在备份操作完成后重命名备份。



== 备份保留选项

您可以选择保留备份副本的天数，或者指定要保留的备份副本数量， ONTAP最多可保留 255 份。例如，您的组织可能要求您保留 10 天的备份副本或 130 份备份副本。

创建策略时，您可以指定备份类型和计划类型的保留选项。

如果您设置了SnapMirror复制，则保留策略将在目标卷上镜像。

SnapCenter会删除具有与计划类型匹配的保留标签的保留备份。如果资源或资源组的计划类型发生更改，则具有旧计划类型标签的备份可能仍保留在系统中。


NOTE: 为了长期保留备份副本，您应该使用SnapVault备份。
