---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: 您可以使用SnapCenter来恢复文件系统备份。文件系统恢复是一个多阶段过程，将所有数据从指定的备份复制到文件系统的原始位置。 
---
= 恢复 Windows 文件系统备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SnapCenter来恢复文件系统备份。文件系统恢复是一个多阶段过程，将所有数据从指定的备份复制到文件系统的原始位置。

.开始之前
* 您必须已经备份文件系统。
* 如果文件系统当前正在执行计划操作（例如备份操作），则必须先取消该操作，然后才能开始恢复操作。
* 您只能将文件系统备份恢复到原始位置，而不能恢复到备用路径。
+
您无法从备份中恢复单个文件，因为恢复的文件系统会覆盖文件系统原始位置上的所有数据。要从文件系统备份恢复单个文件，您必须克隆备份并访问克隆中的文件。

* 您无法恢复系统或启动卷。
* SnapCenter可以在不使集群组脱机的情况下恢复 Windows 集群中的文件系统。


.关于此任务
* SCRIPTS_PATH 是使用插件主机的 SMCoreServiceHost.exe.Config 文件中的 PredefinedWindowsScriptsDirectory 键定义的。
+
如果需要，您可以更改此路径并重新启动 SMcore 服务。为了安全起见，建议您使用默认路径。

+
可以通过 API 从 Swagger 显示该键的值：API /4.7/configsettings

+
您可以使用 GET API 来显示键的值。不支持 SET API。

* 对于SnapMirror活动同步恢复操作，您必须从主位置选择备份。
* 对于ONTAP 9.12.1 及以下版本、作为恢复的一部分从SnapLock Vault 快照创建的克隆将继承SnapLock Vault 到期时间。存储管理员应在SnapLock到期后手动清理克隆。


[role="tabbed-block"]
====
.SnapCenter UI
--
.步骤
. 在左侧导航窗格中，单击“*资源*”，然后从列表中选择适当的插件。
. 要过滤资源列表，请选择文件系统和资源组选项。
. 从列表中选择一个资源组，然后单击“*恢复*”。
. 在备份页面中，选择是否要从主存储系统还是辅助存储系统恢复，然后选择要恢复的备份。
. 在还原向导中选择您的选项。
. 您可以分别输入希望SnapCenter在还原操作之前或之后运行的前置脚本或后置脚本的路径和参数。
+
例如，您可以运行脚本来更新 SNMP 陷阱、自动发出警报、发送日志等。

+

NOTE: 前言或后记路径不应包含驱动器或共享。该路径应相对于 SCRIPTS_PATH。

. 在通知页面中，选择以下选项之一：
+
|===
| 对于这个领域... | 操作 


 a| 
将SnapCenter服务器事件记录到存储系统 syslog
 a| 
选择此选项可将SnapCenter Server 事件记录到存储系统的系统日志中。



 a| 
向存储系统发送操作失败的AutoSupport通知
 a| 
选择此选项可使用AutoSupport将有关任何失败操作的信息发送到NetApp 。



 a| 
电子邮件偏好
 a| 
选择“*始终*”、“*失败时*”或“*失败或警告时*”在恢复备份后向收件人发送电子邮件消息。输入 SMTP 服务器、默认电子邮件主题行以及收件人和发件人电子邮件地址。

|===
. 查看摘要，然后单击“*完成*”。
. 通过单击“*监视*”>“*作业*”来监视操作进度。



IMPORTANT: 如果恢复的文件系统包含数据库，那么您还必须恢复该数据库。如果不恢复数据库，那么您的数据库可能处于无效状态。有关恢复数据库的信息，请参阅该数据库的数据保护指南。

--
.PowerShell cmdlet
--
.步骤
. 使用 Open-SmConnection cmdlet 为指定用户启动与SnapCenter服务器的连接会话。
+
[listing]
----
PS C:\> Open-Smconnection
----
. 使用 Get-SmBackup 和 Get-SmBackupReport cmdlet 检索有关要还原的一个或多个备份的信息。
+
此示例显示有关所有可用备份的信息：

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
此示例显示有关 2015 年 1 月 29 日至 2015 年 2 月 3 日备份的详细信息：

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. 使用 Restore-SmBackup cmdlet 从备份中还原数据。
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


可以通过运行_Get-Help command_name_来获取有关可与 cmdlet 一起使用的参数及其描述的信息。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter软件 Cmdlet 参考指南"^]。

--
====