---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 在添加主机和安装插件包之前，您必须完成所有要求。适用于 SAP HANA 数据库的SnapCenter插件可在 Windows 和 Linux 环境中使用。 
---
= 添加主机和安装适用于 SAP HANA 数据库的SnapCenter插件的先决条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在添加主机和安装插件包之前，您必须完成所有要求。适用于 SAP HANA 数据库的SnapCenter插件可在 Windows 和 Linux 环境中使用。

* 您必须在主机上安装 Java 11。
+

NOTE: IBM Java 在 Windows 和 Linux 主机上不受支持。

* 主机上必须安装有SAP HANA数据库交互终端（HDBSQL客户端）。
* 对于 Windows，插件创建者服务应该使用“LocalSystem”Windows 用户运行，这是以域管理员身份安装 SAP HANA 数据库插件时的默认行为。
* 对于 Windows，应以 SYSTEM 用户身份创建用户存储密钥。
* 在 Windows 主机上安装插件时，如果指定非内置的凭据或用户属于本地工作组用户，则必须在主机上禁用 UAC。适用于 Microsoft Windows 的SnapCenter插件将默认与 Windows 主机上的 SAP HANA 插件一起部署。
* 对于 Linux 主机，HDB 安全用户存储密钥以 HDBSQL OS 用户身份访问。
* SnapCenter服务器应该可以访问 SAP HANA 数据库主机插件的 8145 或自定义端口。




== Windows 主机

* 您必须拥有具有本地管理员权限的域用户，并在远程主机上拥有本地登录权限。
* 在 Windows 主机上安装适用于 SAP HANA 数据库的插件时，适用于 Microsoft Windows 的SnapCenter插件会自动安装。
* 您必须为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须在 Windows 主机上安装 Java 11。
+
http://www.java.com/en/download/manual.jsp["下载适用于所有操作系统的 JAVA"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 互操作性表工具"]





== Linux 主机

* 您必须为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须在 Linux 主机上安装 Java 11。
+
http://www.java.com/en/download/manual.jsp["下载适用于所有操作系统的 JAVA"]

+
https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["NetApp 互操作性表工具"]

* 对于在 Linux 主机上运行的 SAP HANA 数据库，在安装 SAP HANA 数据库插件时，会自动安装适用于 UNIX 的SnapCenter插件。
* 您应该将 *bash* 作为插件安装的默认 shell。




== 补充命令

要在 SAP HANA 的SnapCenter插件上运行补充命令，必须将其包含在 _allowed_commands.config_ 文件中。

* Windows 主机上的默认位置：_C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc\allowed_commands.config_
* Linux 主机上的默认位置：_/opt/ NetApp/snapcenter/scc/etc/allowed_commands.config_


要允许插件主机上的补充命令，请在编辑器中打开_allowed_commands.config_文件。每个命令在单独的行上输入，并且命令不区分大小写。确保指定完全限定的路径名，并且如果路径名包含空格，则将其括在引号 (") 中。

例如：

命令：mount

命令：umount

命令：“C:\Program Files\ NetApp\SnapCreator 命令\sdcli.exe”

命令：myscript.bat

如果不存在 _allowed_commands.config_ 文件，命令或脚本执行将被阻止，并且工作流将失败并出现以下错误：

不允许执行“[/mnt/mount -a]。通过在插件主机上的文件 %s 中添加命令来授权。”

如果命令或脚本不在_allowed_commands.config_中，则命令或脚本的执行将被阻止，并且工作流将失败并出现以下错误：

不允许执行“[/mnt/mount -a]。通过在插件主机上的文件 %s 中添加命令来授权。”


NOTE: 您不应使用通配符 (*) 来允许所有命令。



== 为 Linux 主机的非 root 用户配置 sudo 权限

SnapCenter 2.0 及更高版本允许非 root 用户安装适用于 Linux 的SnapCenter插件包并启动插件进程。插件进程将以有效的非 root 用户身份运行。您应该为非 root 用户配置 sudo 权限以提供对多个路径的访问。

*您需要什么*

* Sudo 版本 1.8.7 或更高版本。
* 如果 umask 为 0027，请确保 java 文件夹及其内部的所有文件的权限为 555。否则插件安装可能会失败。
* 对于非root用户，请确保非root用户的名称和用户所在组的名称相同。
* 编辑_/etc/ssh/sshd_config_文件，配置消息认证码算法：MACs hmac-sha2-256、MACs hmac-sha2-512。
+
更新配置文件后重新启动sshd服务。

+
示例：

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*关于此任务*

您应该为非 root 用户配置 sudo 权限以提供对以下路径的访问权限：

* /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin
* /custom_location/ NetApp/snapcenter/spl/安装/插件/卸载
* /custom_location/ NetApp/snapcenter/spl/bin/spl


*步骤*

. 登录到要安装适用于 Linux 的SnapCenter插件包的 Linux 主机。
. 使用 visudo Linux 实用程序将以下行添加到 /etc/sudoers 文件。
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+

NOTE: 如果您有 RAC 设置，以及其他允许的命令，您应该将以下内容添加到 /etc/sudoers 文件：“/<crs_home>/bin/olsnodes”



您可以从_/etc/oracle/olr.loc_文件中获取_crs_home_的值。

_LINUX_USER_ 是您创建的非 root 用户的名称。

您可以从 *sc_unix_plugins_checksum.txt* 文件中获取 _checksum_value_，该文件位于：

* _C:\ProgramData\ NetApp\ SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_（如果SnapCenter Server 安装在 Windows 主机上）。
* _/opt/ NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ 如果SnapCenter Server 安装在 Linux 主机上。。



IMPORTANT: 该示例仅应作为创建您自己的数据的参考。
