---
permalink: protect-hana/task_prepare_multitenant_database_containers_for_data_protection.html 
sidebar: sidebar 
keywords: multitenant database containers 
summary: '对于直接在SnapCenter中注册的 SAP HANA 主机，安装或升级 SAP HANA 数据库的SnapCenter插件将触发主机上资源的自动发现。安装或升级插件后，对于位于插件主机上的每个多租户数据库容器 (MDC) 资源，将自动发现具有不同 GUID 格式的另一个 MDC 资源并在SnapCenter中注册。新资源将处于“锁定”状态。' 
---
= 准备多租户数据库容器以进行数据保护
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于直接在SnapCenter中注册的 SAP HANA 主机，安装或升级 SAP HANA 数据库的SnapCenter插件将触发主机上资源的自动发现。安装或升级插件后，对于位于插件主机上的每个多租户数据库容器 (MDC) 资源，将自动发现具有不同 GUID 格式的另一个 MDC 资源并在SnapCenter中注册。新资源将处于“锁定”状态。

.关于此任务
例如，在SnapCenter 4.2 中，如果 E90 MDC 资源位于插件主机上并手动注册，则升级到SnapCenter 4.3 后，将在SnapCenter中发现并注册另一个具有不同 GUID 的 E90 MDC 资源。


NOTE: 与SnapCenter 4.2 及更早版本的资源相关的备份必须保留，直到保留期到期。保留期到期后，您可以删除旧的 MDC 资源并继续管理新的自动发现的 MDC 资源。

`Old MDC resource`是SnapCenter 4.2 或更早版本中手动添加的插件主机的 MDC 资源。

执行以下步骤开始使用SnapCenter 4.3 中发现的新资源进行数据保护操作：

.步骤
. 在“资源”页面中，选择已将备份添加到早期SnapCenter版本的旧 MDC 资源，然后从“拓扑”页面将其置于“维护模式”。
+
如果资源是资源组的一部分，则将资源组置于“维护模式”。

. 通过从“资源”页面中选择新资源来配置升级到SnapCenter 4.3 后发现的新 MDC 资源。
+
“新 MDC 资源”是SnapCenter服务器和插件主机升级到 4.3 后发现的新 MDC 资源。对于给定主机，新的 MDC 资源可以被标识为与旧 MDC 资源具有相同 SID 的资源，并且在资源页面中旁边带有红色挂锁图标。

. 通过选择保护策略、计划和通知设置来保护升级到SnapCenter 4.3 后发现的新 MDC 资源。
. 根据保留设置删除在SnapCenter 4.2 或更早版本中创建的备份。
. 从拓扑页面中删除资源组。
. 从资源页面中删除旧的 MDC 资源。
+
例如，如果主快照保留期为 7 天，次要快照保留期为 45 天，则 45 天结束后，删除所有备份后，必须删除资源组和旧的 MDC 资源。



.相关信息
link:task_configure_hdb_user_store_key_and_hdbsql_os_user_for_the_sap_hana_database.html["为 SAP HANA 数据库配置 HDB 用户存储密钥和 HDBSQL OS 用户"]

link:task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["在拓扑页面中查看 SAP HANA 数据库备份和克隆"]
