---
sidebar: sidebar 
permalink: sc-automation/concept_rest_web_services_foundation.html 
keywords: uri endpoints, http messages, json format 
summary: REST 是一种创建分布式 Web 应用程序的风格。当应用于 Web 服务 API 的设计时，它可以建立一套用于公开基于服务器的资源并管理其状态的技术和最佳实践。它采用主流协议和标准，为管理SnapCenter提供灵活的基础。 
---
= REST Web 服务基础
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
表述性状态传输 (REST) 是一种用于创建分布式 Web 应用程序的样式。当应用于 Web 服务 API 的设计时，它可以建立一套用于公开基于服务器的资源并管理其状态的技术和最佳实践。它采用主流协议和标准，为管理SnapCenter提供灵活的基础。



== 资源和国家代表

资源是基于 Web 系统的基本组件。创建 REST Web 服务应用程序时，早期设计任务包括：



=== 识别系统或基于服务器的资源

每个系统都会使用和维护资源。资源可以是文件、业务事务、流程或管理实体。基于 REST Web 服务设计应用程序的首要任务之一就是识别资源。



=== 资源状态和相关状态操作的定义

资源总是处于有限数量的状态之一。应该明确定义状态以及用于影响状态变化的相关操作。



== URI 端点

每个 REST 资源都必须使用定义明确的寻址方案进行定义和提供。资源所在和标识的端点使用统一资源标识符 (URI)。URI

提供了一个通用框架，用于为网络中的每个资源创建唯一名称。统一资源定位符 (URL) 是一种用于 Web 服务识别和访问资源的 URI。资源通常以类似于文件目录的层级结构公开。



== HTTP 消息

超文本传输协议 (HTTP) 是 Web 服务客户端和服务器用来交换资源请求和响应消息的协议。

作为设计 Web 服务应用程序的一部分，HTTP 方法被映射到资源和相应的状态管理操作。HTTP 是无状态的。因此，要将一组相关的请求和响应关联为一个事务的一部分，必须在请求和响应数据流携带的 HTTP 标头中包含附加信息。



== JSON 格式

虽然可以通过多种方式在 Web 服务客户端和服务器之间构建和传输信息，但最流行的选项是 JavaScript 对象表示法 (JSON)。

是一种行业标准，用于以纯文本表示简单数据结构，并用于传输描述资源的状态信息。SnapCenter REST API 使用 JSON 来格式化每个 HTTP 请求和响应主体中携带的数据。
