= 管理插件密钥库的密码以及正在使用的 CA 签名密钥对的别名
:allow-uri-read: 


您应该管理插件密钥库及其证书的密码，配置 CA 证书，将根证书或中间证书配置到插件信任库，并使用SnapCenter插件服务将 CA 签名密钥对配置到插件信任库以激活已安装的数字证书。

插件使用位于 _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_ 的文件 _keystore.jks_ 作为其信任库和密钥库。



== 管理插件密钥库的密码以及正在使用的 CA 签名密钥对的别名

.步骤
. 您可以从插件代理属性文件中检索插件密钥库默认密码。
+
它是与密钥_KEYSTORE_PASS_对应的值。

. 更改密钥库密码：
+
_keytool -storepasswd -keystore 密钥库.jks_

+

NOTE: 如果 Windows 命令提示符无法识别“keytool”命令，请将 keytool 命令替换为其完整路径。

+
_C:\Program Files\Java\<jdk_version>\bin\keytool.exe”-storepasswd -keystore keystore.jks_

. 将密钥库中所有私钥条目别名的密码更改为与密钥库相同的密码：
+
_keytool -keypasswd -alias“别名在证书中”-keystore keystore.jks_

+
对 _agent.properties_ 文件中的密钥 KEYSTORE_PASS 进行相同的更新。

. 修改密码后重启服务。
+

NOTE: 插件密钥库的密码和私钥的所有相关别名的密码应该相同。





== 配置根证书或中间证书以插入信任库

您应该配置没有私钥的根证书或中间证书来插入信任库。

.步骤
. 导航到包含插件密钥库的文件夹 _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_
. 找到文件“keystore.jks”。
. 列出密钥库中添加的证书：
+
_keytool -list -v -keystore keystore.jks_

. 添加根证书或中间证书：
+
_keytool -import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks_

. 配置根证书或中间证书以插入信任库后重新启动服务。



NOTE: 您应该添加根 CA 证书，然后添加中间 CA 证书。



== 配置 CA 签名密钥对以插入信任库

您应该将 CA 签名的密钥对配置到插件信任库。

.步骤
. 导航到包含插件密钥库的文件夹 _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_
. 找到文件_keystore.jks_。
. 列出密钥库中添加的证书：
+
_keytool -list -v -keystore keystore.jks_

. 添加具有私钥和公钥的 CA 证书。
+
_keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS_

. 列出密钥库中添加的证书。
+
_keytool -list -v -keystore keystore.jks_

. 验证密钥库是否包含与添加到密钥库的新 CA 证书相对应的别名。
. 将添加的CA证书私钥密码更改为keystore密码。
+
默认插件密钥库密码是 agent.properties 文件中密钥 KEYSTORE_PASS 的值。

+
_keytool -keypasswd -alias“别名在CA证书中的名称”-keystore keystore.jks_

. 在_agent.properties_文件中配置来自CA证书的别名。
+
根据键 SCC_CERTIFICATE_ALIAS 更新此值。

. 配置 CA 签名密钥对以插入信任库后重新启动服务。




== 为SnapCenter插件配置证书吊销列表 (CRL)

.关于此任务
* 要下载相关 CA 证书的最新 CRL 文件，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["如何更新SnapCenter CA 证书中的证书吊销列表文件"]。
* SnapCenter插件将在预配置的目录中搜索 CRL 文件。
* SnapCenter插件的 CRL 文件的默认目录是 _'C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\ etc\crl'_。


.步骤
. 您可以根据键 CRL_PATH 修改和更新 _agent.properties_ 文件中的默认目录。
. 您可以在此目录中放置多个 CRL 文件。
+
将根据每个 CRL 验证传入的证书。


