---
permalink: tech-refresh/task_tech_refresh_server_host.html 
sidebar: sidebar 
keywords: tech refresh, SnapCenter Server, cmdlet, APIs, F5, rollback, decommission, disaster recovery, standalone 
summary: 在新主机上安装相同版本的SnapCenter Server，然后运行 ​​API 或执行 cmdlet 从旧服务器备份SnapCenter并在新服务器上恢复它。 
---
= SnapCenter Server 主机的技术更新
:allow-uri-read: 


[role="lead"]
当SnapCenter Server 主机需要刷新时，您可以在新主机上安装相同版本的SnapCenter Server，然后运行 ​​API 从旧服务器备份SnapCenter并在新服务器上恢复它。

.步骤
. 部署新主机并执行以下任务：
+
.. 安装相同版本的SnapCenter服务器。
.. （可选）配置 CA 证书并启用双向 SSL。更多信息，请参阅 https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html["配置 CA 证书"]和 https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html["配置并启用双向 SSL"]。
.. （可选）配置多重身份验证。有关更多信息，请参阅 https://docs.netapp.com/us-en/snapcenter/install/enable_multifactor_authentication.html["启用多重身份验证"] 。


. 以SnapCenter管理员用户身份登录。
. 使用以下 API 在旧主机上创建SnapCenter服务器的备份： `/<snapcenter_version>/server/backup`或 cmdlet：_New-SmServerBackup_。
+

NOTE: 在进行备份之前，暂停所有计划的作业并确保没有作业正在运行。

+

IMPORTANT: 如果要在新的域上运行的SnapCenter服务器上恢复备份，则在进行备份之前，您应该在旧的SnapCenter主机中添加新的域用户并分配SnapCenter管理员角色。

. 将备份从旧主机复制到新主机。
. 使用以下 API 在新主机上还原SnapCenter服务器的备份： `/<snapcenter_version>/server/restore`或 cmdlet：_Restore-SmServerBackup_。
+
默认情况下，恢复将更新所有主机中的新SnapCenter服务器 URL。如果您想跳过更新，请使用 _-SkipSMSURLInHosts_ 属性，并通过运行以下 API 单独更新服务器 URL： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。

+

NOTE: 如果插件主机无法解析服务器主机名，请登录到每个插件主机，并以 <New IP> SC_Server_Name 格式添加新 IP 的 _etc/host_ 条目。

+

NOTE: 服务器 _etc/host_ 条目将不会被恢复。您可以从旧服务器手动恢复它。

+
如果在新的域上运行的 SnpCenter 服务器上恢复了备份，并且想要继续使用旧域用户，则应在新的SnapCenter服务器上注册旧域。

+

NOTE: 如果您已手动更新旧SnapCenter主机中的 web.config 文件，则更新将不会复制到新主机。您应该在新主机的 web.config 文件中手动进行相同的更改。

. 如果您跳过了更新SnapCenter服务器 URL 或在还原过程中任何主机关闭，请使用以下 API 更新SnapCenter管理的所有主机或指定主机中的新服务器名称： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。
. 从新的SnapCenter服务器激活所有主机上的计划作业。




== F5 集群中节点的技术更新

您可以通过删除节点并添加新节点来对 F5 集群中的任何节点进行技术更新。如果需要刷新的节点处于活动状态，则将集群的另一个节点设为活动状态，然后删除该节点。

有关如何向 F5 集群添加节点的信息，请参阅 https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["使用 F5 配置SnapCenter服务器以实现高可用性"]。


NOTE: 如果 F5 集群的 url 发生变化，则可以使用以下 API 在所有主机中更新 url： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。



== 停用旧的SnapCenter Server 主机

在验证新的SnapCenter Server 已启动并正在运行且所有插件主机都能够与新的SnapCenter SnapCenter主机。



== 回滚到旧的SnapCenter Server 主机

如果出现任何问题，您可以使用以下 API 更新所有主机中的SnapCenter Server URL，从而恢复旧的SnapCenter Server 主机： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。



== 灾难恢复



=== 独立SnapCenter主机的灾难恢复

您可以通过将服务器备份还原到新主机来执行灾难恢复。

.开始之前
确保您有旧SnapCenter服务器的备份。

.步骤
. 部署新主机并执行以下任务：
+
.. 安装相同版本的SnapCenter服务器。
.. 配置CA证书并启用双向SSL。更多信息，请参阅 https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html["配置 CA 证书"]和 https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html["配置并启用双向 SSL"]。


. 将旧的SnapCenter Server 备份复制到新主机。
. 以SnapCenter管理员用户身份登录。
. 使用以下 API 在新主机上还原SnapCenter服务器的备份： `/<snapcenter_version>/server/restore`或 cmdlet：_Restore-SmServerBackup_。
+
默认情况下，恢复将更新所有主机中的新SnapCenter服务器 URL。如果要跳过更新，请使用 _-SkipSMSURLInHosts_ 属性，并使用以下 API 单独更新服务器 URL： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。

+

NOTE: 如果插件主机无法解析服务器主机名，请登录到每个插件主机，并以 <New IP> SC_Server_Name 格式添加新 IP 的 _etc/host_ 条目。

+

NOTE: 服务器 _etc/host_ 条目将不会被恢复。您可以从旧服务器手动恢复它。

. 如果您跳过了更新 URL 或任何主机在还原过程中关闭，请使用以下 API 更新SnapCenter管理的所有主机或指定主机中的新服务器名称： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。




=== SnapCenter F5 集群的灾难恢复

您可以通过将服务器备份还原到新主机，然后将独立主机转换为集群来执行灾难恢复。

.开始之前
确保您有旧SnapCenter服务器的备份。

.步骤
. 部署新主机并执行以下任务：
+
.. 安装相同版本的SnapCenter服务器。
.. 配置CA证书并启用双向SSL。更多信息，请参阅 https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html["配置 CA 证书"]和 https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html["配置并启用双向 SSL"]。


. 将旧的SnapCenter Server 备份复制到新主机。
. 以SnapCenter管理员用户身份登录。
. 使用以下 API 在新主机上还原SnapCenter服务器的备份： `/<snapcenter_version>/server/restore`或 cmdlet：_Restore-SmServerBackup_。
+
默认情况下，恢复将更新所有主机中的新SnapCenter服务器 URL。如果要跳过更新，请使用 _-SkipSMSURLInHosts_ 属性，并使用以下 API 单独更新服务器 URL： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。

+

NOTE: 如果插件主机无法解析服务器主机名，请登录到每个插件主机，并以 <New IP> SC_Server_Name 格式添加新 IP 的 _etc/host_ 条目。

+

NOTE: 服务器 _etc/host_ 条目将不会被恢复。您可以从旧服务器手动恢复它。

. 如果您跳过了更新 URL 或任何主机在还原过程中关闭，请使用以下 API 更新SnapCenter管理的所有主机或指定主机中的新服务器名称： `/<snapcenter_version>/server/configureurl`或 cmdlet：_Set-SmServerConfig_。
. 将独立主机转换为 F5 集群。
+
有关如何配置 F5 的信息，请参阅 https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["使用 F5 配置SnapCenter服务器以实现高可用性"]。



.相关信息
有关 API 的信息，您需要访问 Swagger 页面。请参阅link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["如何使用 Swagger API 网页访问 REST API"]。

可以通过运行_Get-Help command_name_来获取有关可与 cmdlet 一起使用的参数及其描述的信息。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter软件 Cmdlet 参考指南"^]。
