---
permalink: tech-refresh/task_tech_refresh_storage_system.html 
sidebar: sidebar 
keywords: tech refresh, storage system, 
summary: 通过将数据从旧存储移动到新存储，将新存储安装到相应的主机，然后启动数据库来执行存储系统的技术更新。 
---
= 存储系统技术更新
:allow-uri-read: 


[role="lead"]
当存储进行技术更新时，数据将迁移到新的存储，并且应用程序主机将安装新的存储。如果新存储在SnapCenter中注册， SnapCenter备份工作流将识别新存储并创建快照。

您可以对存储刷新后创建的新备份执行恢复、挂载和克隆。但是，当对存储刷新之前创建的备份执行这些操作时，这些操作将会失败，因为备份具有旧的存储详细信息。您应该运行存储技术刷新 API 或 cmdlet 来使用新的存储详细信息更新SnapCenter中的旧备份。

以下SnapCenter插件支持技术更新：

* 适用于 Microsoft SQL Server 的 SnapCenter 插件
* 适用于 Windows 的SnapCenter插件
* 适用于 Oracle 数据库的 SnapCenter 插件
* 适用于 SAP HANA 数据库的SnapCenter插件
* 适用于 Microsoft Exchange Server 的 SnapCenter 插件


支持的用例包括：

* 主存储刷新
+
支持存储技术更新，以用新存储替换主存储。您不能将现有的辅助存储转换为主存储。

* 二级存储刷新




== 更新主存储的备份

当存储进行技术刷新时，您应该运行存储技术刷新 API 或 cmdlet 以使用新的存储详细信息更新SnapCenter中的旧备份。

.开始之前
由于此工作流修改了SnapCenter存储库中的数据，因此建议备份SnapCenter存储库。如果出现任何数据问题，可以使用备份将SnapCenter存储库恢复到旧状态。

有关更多信息，请参阅 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["备份SnapCenter存储库"] 。

.步骤
. 将数据从旧存储迁移到新存储。
+
有关如何迁移的信息，请参阅：

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["如何将数据迁移到新存储"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["如何复制卷并保留所有 Snapshot 副本？"]


. 将主机置于维护模式。
. 在相应的主机上安装新的存储并启动数据库。
+
新的存储应以与以前相同的方式连接到主机。例如，如果它是作为 SAN 连接的，则需要将其作为 SAN 连接。

+
新的存储需要安装在与旧存储相同的驱动器或路径上。

. 验证所有资源是否已启动并正在运行。
. 在SnapCenter中添加新存储。
+
确保SnapCenter中各个集群的 SVM 名称都是唯一的。如果您在新存储中使用相同的 SVM 名称、并且在执行存储刷新之前可以迁移 SVM 的所有卷、则建议删除旧集群中的 SVM 并在SnapCenter中重新发现旧集群、这将从缓存中删除 SVM。

. 将主机置于生产模式。
. 在SnapCenter中，创建已迁移存储的资源的备份。  SnapCenter需要新的备份来识别最新的存储占用空间，并且它将用于更新现有旧备份的元数据。
+

NOTE: 每当一个新的 LUN 连接到主机时，它都会有一个新的序列号。在发现 Windows 文件系统期间， SnapCenter会将每个唯一序列号视为新资源。在存储技术刷新期间，当新存储中的 LUN 以相同的驱动器号或路径连接到主机时， SnapCenter中 Windows 文件系统的发现会将现有资源标记为已删除，即使它以相同的驱动器号或路径安装，并将新 LUN 显示为新资源。由于资源被标记为已删除，因此SnapCenter中不会考虑对其进行存储技术更新，并且旧资源的所有备份都将丢失。每当发生存储刷新时，对于 Windows 文件系统资源，在执行存储刷新 API 或 cmdlet 之前不应执行资源发现。

. 运行存储刷新 API： `/<snapcenter_version>/techrefresh/primarystorage`或 cmdlet：_Invoke-SmTechRefreshPrimaryStorage_。
+

NOTE: 如果资源配置了启用复制的策略，则存储刷新后的最新备份应该具有辅助存储的详细信息。

+
.. 如果您使用 SQL 故障转移群集实例 (FCI) 设置，则备份将在群集级别维护。您应该提供集群名称作为存储技术更新的输入。
.. 如果您使用 SQL 可用性组 (AG) 设置，则备份将在节点级别维护。您应该提供节点名称作为存储技术更新的输入。
.. 如果您使用 Oracle Real Application Clusters (RAC) 设置，则可以在任何节点上执行存储技术刷新。
+
_IsDryRun_ 属性默认设置为 True。它将识别刷新存储的资源。您可以通过运行 API：“<snapcenter_version>/jobs/{jobid}”或 cmdlet _Get-SmJobSummaryReport_ 来查看资源和更改的存储详细信息。



. 验证存储详细信息后，将 _IsDryRun_ 属性设置为 False 并运行存储刷新 API： `/<snapcenter_version>/techrefresh/primarystorage`或 cmdlet：_Invoke-SmTechRefreshPrimaryStorage_。
+
这将更新旧备份中的存储详细信息。

+
您可以在同一主机上多次运行 API 或 cmdlet，只有在刷新存储时它才会更新旧备份中的存储详细信息。

+

NOTE: 克隆层次结构无法在ONTAP中迁移。如果正在迁移的存储在SnapCenter中具有任何克隆元数据，则克隆的资源将被标记为独立资源。克隆元数据的克隆将被递归删除。

. （可选）如果所有快照都未从旧主存储移动到新主存储，请运行以下 API： `/<snapcenter_version>/hosts/primarybackupsexistencecheck`或 cmdlet _Invoke-SmPrimaryBackupsExistenceCheck_。
+
这将对新的主存储执行快照存在性检查，并将相应的备份标记为不可用于SnapCenter中的任何操作。





== 更新辅助存储的备份

当存储进行技术刷新时，您应该运行存储技术刷新 API 或 cmdlet 以使用新的存储详细信息更新SnapCenter中的旧备份。

.开始之前
由于此工作流修改了SnapCenter存储库中的数据，因此建议备份SnapCenter存储库。如果出现任何数据问题，可以使用备份将SnapCenter存储库恢复到旧状态。

有关更多信息，请参阅 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["备份SnapCenter存储库"] 。

.步骤
. 将数据从旧存储迁移到新存储。
+
有关如何迁移的信息，请参阅：

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["如何将数据迁移到新存储"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["如何复制卷并保留所有 Snapshot 副本？"]


. 在主存储和新的二级存储之间建立SnapMirror关系，并确保关系状态良好。
. 在SnapCenter中，创建已迁移存储的资源的备份。
+
SnapCenter需要新的备份来识别最新的存储占用空间，并且它将用于更新现有旧备份的元数据。

+

IMPORTANT: 您应该等到此操作完成。如果在完成之前继续下一步， SnapCenter将完全丢失旧的辅助快照元数据。

. 成功创建主机中所有资源的备份后，运行辅助存储刷新 API： `/<snapcenter_version>/techrefresh/secondarystorage`或 cmdlet：_Invoke-SmTechRefreshSecondaryStorage_。
+
这将更新给定主机中旧备份的辅助存储详细信息。

+
如果您想在资源级别运行此功能，请单击每个资源的*刷新*以更新辅助存储元数据。

. 成功更新旧备份后，您可以断开旧的辅助存储与主存储的关系。

