---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords: SnapCenter reports 
summary: SnapCenter提供多种报告选项，使您能够监控和管理系统健康和操作成功。 
---
= SnapCenter报告功能概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter提供多种报告选项，使您能够监控和管理系统健康和操作成功。

|===
| 报告类型 | 描述 


 a| 
备份报告
 a| 
备份报告提供有关SnapCenter环境的备份趋势的总体数据、备份成功率以及有关在指定时间内执行的每个备份的一些信息。如果删除了备份，则报告不会显示已删除备份的任何状态信息。备份详细报告提供有关指定备份作业的详细信息，并列出成功备份的资源和失败的资源。



 a| 
克隆报告
 a| 
克隆报告提供有关SnapCenter环境的克隆趋势的总体数据、克隆成功率以及有关在指定时间内执行的每个克隆作业的一些信息。如果删除了克隆，则报告不会显示已删除克隆的任何状态信息。克隆详细报告提供有关指定克隆、克隆主机和克隆作业任务状态的详细信息。如果任务失败，克隆详细报告将显示有关失败的信息。



 a| 
恢复报告
 a| 
恢复报告提供有关恢复作业的总体信息。恢复详细信息报告提供有关指定恢复作业的详细信息，包括主机名、备份名称、作业开始和持续时间以及各个作业任务的状态。如果任务失败，恢复详细报告将显示有关失败的信息。



 a| 
保护报告
 a| 
这些报告提供所有SnapCenter插件实例管理的资源的保护详细信息。此报告提供所有插件实例管理的资源的保护详细信息。您可以查看概览、未受保护资源的详细信息、生成报告时尚未备份的资源、备份操作失败的资源组的资源以及SnapVault状态。



 a| 
定期报告
 a| 
这些报告计划定期运行，例如每天、每周或每月。报告会在指定的日期和时间自动生成，并通过电子邮件发送给相关人员。您可以启用、禁用、修改或删除计划。通过单击“立即运行”按钮，可以按需运行已启用的计划。管理员可以运行任何计划，但生成的报告将包含基于创建该计划的用户提供的权限的数据。

除管理员之外的任何其他用户都可以根据其权限查看或修改计划。如果在添加角色页面中选择了该角色的所有成员都可以看到其他成员的对象选项，则该角色的其他成员将能够查看和修改。

|===


== 访问报告

您可以使用SnapCenter仪表板快速了解系统的运行状况。您可以从仪表板深入了解更多详细信息。或者，您可以直接访问详细报告。

您可以通过以下方法之一访问报告：

* 在左侧导航窗格中，单击“*仪表板*”，然后单击“*上次保护摘要*”饼图以在“报告”页面中查看更多详细信息。
* 在左侧导航窗格中，单击“*报告*”。




== 过滤报告

您可能希望根据所需信息的详细程度和时间跨度，按照一系列参数来过滤报告数据。

*步骤*

. 在左侧导航窗格中，单击“*报告*”。
. 如果未显示参数视图，请单击报告工具栏中的“*切换参数区域*”图标。
. 指定您想要运行报告的时间范围。  + 如果省略结束日期，您将检索所有可用信息。
. 根据以下任意条件过滤报告信息：
+
** 资源组
** 主机
** 策略
** 资源
** 状态
** 插件名称


. 单击“*应用*”。




== 导出或打印报告

导出SnapCenter报告使您能够以多种其他格式查看报告。您还可以打印报告。

*步骤*

. 在左侧导航窗格中，单击“*报告*”。
. 从报告工具栏中执行以下操作之一：
+
** 单击“切换打印预览”图标即可预览可打印的报告。
** 从*导出*图标下拉列表中选择一种格式，将报告导出为其他格式。


. 要打印报告，请单击“*打印*”图标。
. 要查看特定的报告摘要，请滚动到报告的相应部分。




== 设置电子邮件通知的 SMTP 服务器

您可以指定用于向您自己或其他人发送数据保护作业报告的 SMTP 服务器。您还可以发送测试电子邮件来验证配置。这些设置将全局应用于您配置电子邮件通知的任何SnapCenter作业。

此选项配置 SMTP 服务器以发送所有数据保护作业报告。但是，如果您希望定期将特定资源的SnapCenter数据保护作业更新发送给您自己或其他人，以便您可以监视这些更新的状态，则可以在创建资源组时配置通过电子邮件发送SnapCenter报告的选项。

*步骤*

. 在左侧导航窗格中，单击“*设置*”。
. 在设置页面中，单击*全局设置*。
. 输入 SMTP 服务器并单击*保存*。
. 要发送测试电子邮件，请输入您要发送电子邮件的电子邮件地址，输入主题，然后单击“*发送*”。




== 配置通过电子邮件发送报告的选项

如果您希望定期将SnapCenter数据保护作业更新发送给自己或他人，以便监控这些更新的状态，则可以在创建资源组时配置通过电子邮件发送SnapCenter报告的选项。

.开始之前
您必须在“设置”下的“全局设置”页面中配置您的 SMTP 服务器。

*步骤*

. 在左侧导航窗格中，单击“*资源*”，然后从列表中选择适当的插件。
. 选择您要查看的资源类型并单击*新建资源组*，或者选择现有的资源组并单击*修改*为现有资源组配置电子邮件报告。
. 在新资源组向导的通知面板中，从下拉菜单中选择是否始终接收报告、在失败时接收报告、在失败或警告时接收报告。
. 输入电子邮件的发件地址、收件人地址以及电子邮件的主题。

