---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: '从SnapCenter左侧导航窗格中，仪表板可让您初步了解系统的运行状况，包括最近的作业活动、警报、保护摘要、存储效率和使用情况、 SnapCenter作业的状态（备份、克隆、还原）、独立和 Windows 集群主机的配置状态、 SnapCenter管理的存储虚拟机 (SVM) 数量以及许可证容量。' 
---
= 仪表板概览
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从SnapCenter左侧导航窗格中，仪表板可让您初步了解系统的运行状况，包括最近的作业活动、警报、保护摘要、存储效率和使用情况、 SnapCenter作业的状态（备份、克隆、还原）、独立和 Windows 集群主机的配置状态、 SnapCenter管理的存储虚拟机 (SVM) 数量以及许可证容量。

仪表板视图中显示的信息取决于分配给当前登录到SnapCenter 的用户的角色。如果用户没有权限查看某些信息，则可能不会显示该内容。

在许多情况下，您可以通过将鼠标悬停在 *i* 上来查看有关显示器的更多信息。在某些情况下，仪表板显示中的信息会链接到SnapCenter GUI 页面中的详细源信息，例如资源、监视器和报告。



== 最近的工作活动

“最近的作业活动”图块显示您有权访问的任何备份、还原和克隆作业的最新作业活动。此显示中的作业具有以下状态之一：已完成、警告、失败、正在运行、排队和已取消。

将鼠标悬停在某个工作上可以提供更多信息。您可以通过单击特定的作业编号来查看其他作业信息，该编号会将您重定向到“监视”页面。从那里，您可以获取作业详细信息或日志信息，并生成特定于该作业的报告。

单击“查看全部”可查看所有SnapCenter作业的历史记录。



== 警报

警报磁贴显示主机和SnapCenter服务器的最新未解决的严重和警告警报。

严重和警告类别警报的总数显示在显示屏顶部。单击“严重”或“警告”总数会将您重定向到“警报”页面，并在“警报”页面中应用特定的过滤器。

单击特定警报会将您重定向到“警报”页面，以查看有关该警报的详细信息。单击显示屏底部的“查看全部”会将您重定向到“警报”页面，以查看所有警报的列表。



== 最新保护摘要

最新保护摘要图块为您提供您有权访问的所有实体的保护状态。默认情况下，显示设置为提供所有插件的状态。提供以快照形式备份到主存储的资源以及使用SnapMirror和SnapVault技术备份到二级存储的资源的状态信息。二级存储的保护状态信息的可用性取决于所选的插件类型。


NOTE: 如果您使用镜像保管库保护策略，则保护摘要的计数器将显示在SnapVault摘要图表中，而不是SnapMirror图表中。

通过从下拉菜单中选择插件，可以查看单个插件的保护状态。环形图显示所选插件的受保护资源百分比。点击环形图切片会将您重定向到“报告”>“插件”页面，该页面提供指定插件所有主存储和二级存储活动的详细报告。


IMPORTANT: 有关二级存储的报告仅适用于SnapVault ；不支持SnapMirror报告。


NOTE: SAP HANA 为快照的主存储和辅助存储提供保护状态信息。对于基于文件的备份，仅主存储保护状态可用。

|===
| 保护状态 | 主存储 | 二级存储 


 a| 
失败
 a| 
属于资源组的实体的数量，其中资源组已运行备份，但备份失败。
 a| 
备份未能传输至辅助目标的实体数量。



 a| 
成功
 a| 
资源组中已成功备份的实体的数量。
 a| 
已成功传输到辅助目标的具有备份的实体的数量。



 a| 
未配置
 a| 
不属于任何资源组且尚未备份的实体的数量。
 a| 
属于一个或多个资源组且未配置为将备份传输到辅助目标的实体的数量。



 a| 
未发起
 a| 
属于资源组但尚未运行备份的实体的数量。
 a| 
不适用。

|===

NOTE: 如果您使用SnapCenter Server 4.2 和早期版本的插件（早于 4.2）来创建备份，则 *最新保护摘要* 图块不会显示这些备份的SnapMirror保护状态。



== 作业

作业磁贴为您提供了您有权访问的备份、还原和克隆作业的摘要。您可以使用下拉菜单自定义任何报告的时间范围。时间范围选项固定为过去 24 小时、过去 7 天和过去 30 天。默认报告显示过去 7 天内运行的数据保护作业。

备份、恢复和克隆作业信息显示在环形图中。单击甜甜圈切片会将您重定向到“监视”页面，其中作业过滤器已预先应用于选择。

|===
| 作业状态 | 描述 


 a| 
失败
 a| 
失败的作业数量。



 a| 
警告
 a| 
遇到错误的作业数量。



 a| 
成功
 a| 
已成功完成的作业数量。



 a| 
正在运行
 a| 
当前正在运行的作业数量。

|===


== 存储

存储磁贴显示 90 天内保护作业所消耗的主存储和辅助存储，以图形方式描绘消耗趋势，并计算主存储节省量。存储信息每24小时凌晨12点更新一次

当天的消耗总量（包括SnapCenter中可用的备份总数以及这些备份占用的大小）将显示在显示屏顶部。一个备份可以有多个与之关联的快照，并且计数将反映相同的情况。这适用于主快照和次快照。例如，您创建了 10 个备份，其中 2 个由于基于策略的备份保留而被删除，1 个备份被您明确删除。因此，将显示 7 个备份的数量以及这 7 个备份占用的大小。

主存储的存储节省系数是逻辑容量（克隆和快照节省加上消耗的存储）与主存储的物理容量的比率。条形图显示了存储节省情况。

该折线图分别绘制了连续 90 天期间每天的主存储和二级存储消耗情况。将鼠标悬停在图表上即可查看每日的详细结果。


NOTE: 如果您使用SnapCenter Server 4.2 和早期版本的插件（早于 4.2）来创建备份，则 *存储* 图块不会显示备份数量、这些备份消耗的存储空间、快照节省、克隆节省和快照大小。



== 配置

配置磁贴提供SnapCenter正在管理且您有权访问的所有活动独立主机和 Windows 群集主机的综合状态信息。这包括与这些主机相关的插件状态信息。

单击“主机”旁边的数字会将您重定向到“主机”页面中的“托管主机”部分。从那里，您可以获得所选主机的详细信息。

此外，此显示还显示了SnapCenter正在管理且您有权访问的独立ONTAP SVM 和集群ONTAP SVM 的总和。单击 SVM 旁边的数字会将您重定向到“存储系统”页面。从那里，您可以获得所选 SVM 的详细信息。

主机配置状态显示为红色（严重）、黄色（警告）和绿色（活动），以及每种状态下的主机数量。为每个状态提供状态消息。

|===
| 配置状态 | 描述 


 a| 
强制升级
 a| 
运行不受支持的插件且需要升级的主机数量。不受支持的插件与此版本的SnapCenter不兼容。



 a| 
强制迁移
 a| 
运行不受支持的插件且需要迁移的主机数量。不受支持的插件与此版本的SnapCenter不兼容。



 a| 
未安装任何插件
 a| 
添加成功但需要安装插件或插件安装失败的主机数量。



 a| 
已暂停
 a| 
计划暂停和正在维护的主机数量。



 a| 
已停止
 a| 
已启动但插件服务未运行的主机数量。



 a| 
主机宕机
 a| 
已关闭或无法访问的主机数量。



 a| 
可升级（可选）
 a| 
可升级新版本插件包的主机数量。



 a| 
可迁移（可选）
 a| 
可供迁移较新版本插件的主机数量。



 a| 
配置日志目录
 a| 
必须配置日志目录以便 SCSQL 进行事务日志备份的主机数量。



 a| 
配置 VMware 插件
 a| 
需要添加适用SnapCenter Plug-in for VMware vSphere的主机数量。



 a| 
未知
 a| 
已注册但尚未触发安装的主机数量。



 a| 
正在运行
 a| 
已启动且正在运行插件的主机数量。对于 SCSQL 插件，需要配置日志目录和虚拟机管理程序。



 a| 
安装\卸载插件
 a| 
正在进行插件安装或卸载的主机数量。

|===