---
permalink: protect-postgresql/add-hosts-and-install-plug-in-packages-on-remote-hosts-postgresql.html 
sidebar: sidebar 
keywords: credentials 
summary: 您必须使用SnapCenter添加主机页面来添加主机，然后安装插件包。插件会自动安装在远程主机上。您可以为单个主机或集群添加主机并安装插件包。 
---
= 添加主机并在远程主机上安装插件包
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须使用SnapCenter添加主机页面来添加主机，然后安装插件包。插件会自动安装在远程主机上。您可以添加主机并为单个主机安装插件包。

.开始之前
* 如果SnapCenter Server 主机的操作系统是 Windows 2019，而插件主机的操作系统是 Windows 2022，则应执行以下操作：
+
** 升级到 Windows Server 2019（操作系统内部版本 17763.5936）或更高版本
** 升级到 Windows Server 2022（操作系统内部版本 20348.2402）或更高版本


* 您必须是分配有插件安装和卸载权限的角色的用户，例如SnapCenter管理员角色。
* 在 Windows 主机上安装插件时，如果指定非内置的凭据，或者用户属于本地工作组用户，则必须在主机上禁用 UAC。
* 您应该确保消息队列服务正在运行。
* 管理文档包含有关管理主机的信息。
* 如果您使用组托管服务帐户 (gMSA)，则应使用管理权限配置 gMSA。
+
link:../protect-postgresql/configure-gMSA-on-windows-server-2012-or-later.html["在 Windows Server 2016 或更高版本上为 PostgreSQL 配置组托管服务帐户"]



.关于此任务
* 您不能将SnapCenter服务器作为插件主机添加到另一个SnapCenter服务器。


.步骤
. 在左侧导航窗格中，单击“*主机*”。
. 验证顶部的“*托管主机*”选项卡是否被选中。
. 单击“*添加*”。
. 在“主机”页面中，执行以下操作：
+
|===
| 对于这个领域... | 操作 


 a| 
主机类型
 a| 
选择主机类型：

** Windows
** Linux
+

NOTE: PostgreSQL 插件安装在 PostgreSQL 客户端主机上，该主机可以是 Windows 系统，也可以是 Linux 系统。





 a| 
主机名
 a| 
输入通信主机名。输入主机的完全限定域名 (FQDN) 或 IP 地址。 SnapCenter依赖于 DNS 的正确配置。因此，最佳做法是输入 FQDN。



 a| 
凭据
 a| 
选择您创建的凭证名称或创建新的凭证。该凭证必须具有远程主机的管理权限。有关详细信息，请参阅有关创建凭证的信息。

您可以将光标放在您提供的凭证名称上来查看有关凭证的详细信息。


NOTE: 凭据身份验证模式由您在添加主机向导中指定的主机类型决定。

|===
. 在选择要安装的插件部分中，选择要安装的插件。
+
使用 REST API 安装 PostgreSQL 插件时，必须传递版本为 3.0。例如，PostgreSQL:3.0

. （可选）单击“更多选项”。
+
|===
| 对于这个领域... | 操作 


 a| 
端口
 a| 
保留默认端口号或指定端口号。默认端口号是 8145如果SnapCenter服务器安装在自定义端口上，则该端口号将显示为默认端口。


NOTE: 如果您手动安装了插件并指定了自定义端口，则必须指定相同的端口。否则，操作失败。



 a| 
安装路径
 a| 
PostgreSQL 插件安装在 PostgreSQL 客户端主机上，该主机可以是 Windows 系统，也可以是 Linux 系统。

** 对于适用于 Windows 的SnapCenter插件包，默认路径为 C:\Program Files\ NetApp\ SnapCenter。您也可以选择自定义路径。
** 对于适用于 Linux 的SnapCenter插件包，默认路径为 /opt/ NetApp/snapcenter。您也可以选择自定义路径。




 a| 
跳过预安装检查
 a| 
如果您已经手动安装了插件并且不想验证主机是否满足安装插件的要求，请选中此复选框。



 a| 
添加集群中的所有主机
 a| 
选中此复选框可添加所有集群节点。



 a| 
使用组托管服务帐户 (gMSA) 运行插件服务
 a| 
对于 Windows 主机，如果要使用组托管服务帐户 (gMSA) 来运行插件服务，请选中此复选框。


NOTE: 以以下格式提供 gMSA 名称：domainName\accountName$。


NOTE: gMSA 将仅用作 Windows 服务的SnapCenter插件的登录服务帐户。

|===
. 单击“*提交*”。
+
如果您未选中“跳过预检查”复选框，则会验证主机是否满足安装插件的要求。系统会根据最低要求验证磁盘空间、RAM、PowerShell 版本、.NET 版本、位置（对于 Windows 插件）和 Java 版本（对于 Linux 插件）。如果不满足最低要求，则会显示相应的错误或警告消息。

+
如果错误与磁盘空间或 RAM 有关，您可以更新位于 C:\Program Files\ NetApp\ SnapCenter WebApp 的 web.config 文件以修改默认值。如果错误与其他参数有关，则必须修复该问题。

+

NOTE: 在 HA 设置中，如果您要更新 web.config 文件，则必须在两个节点上更新该文件。

. 如果主机类型为Linux，请验证指纹，然后单击*确认并提交*。
+
在集群设置中，您应该验证集群中每个节点的指纹。

+

NOTE: 即使之前已将同一主机添加到SnapCenter并且已确认指纹，也必须进行指纹验证。

. 监控安装进度。
+
** 对于 Windows 插件，安装和升级日志位于：_C:\Windows\ SnapCenter plugin\Install_<JOBID>\_
** 对于 Linux 插件，安装日志位于：_/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Install_<JOBID>.log_，升级日志位于：_/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Upgrade_<JOBID>.log_



