---
permalink: install/concept_high_availability_for_snapcenter_mysql_repository.html 
sidebar: sidebar 
keywords: SnapCenter, MySQL high availability 
summary: 'MySQL 复制是 MySQL 服务器的一项功能，它使您能够将数据从一个 MySQL 数据库服务器（主服务器）复制到另一个 MySQL 数据库服务器（从服务器）。  SnapCenter仅在两个启用网络负载平衡 (NLB) 的节点上支持 MySQL 复制以实现高可用性。' 
---
= SnapCenter MySQL 存储库的高可用性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 复制是 MySQL 服务器的一项功能，它使您能够将数据从一个 MySQL 数据库服务器（主服务器）复制到另一个 MySQL 数据库服务器（从服务器）。  SnapCenter仅在两个启用网络负载平衡 (NLB) 的节点上支持 MySQL 复制以实现高可用性。

SnapCenter在主存储库上执行读取或写入操作，并在主存储库出现故障时将其连接路由到从属存储库。然后从属存储库将成为主存储库。  SnapCenter还支持反向复制，该功能仅在故障转移期间启用。

如果要使用 MySQL 高可用性 (HA) 功能，则必须在第一个节点上配置网络负载均衡器 (NLB)。 MySQL 存储库作为安装的一部分安装在此节点上。在第二个节点上安装SnapCenter时，您必须加入第一个节点的 F5 并在第二个节点上创建 MySQL 存储库的副本。

SnapCenter提供 _Get-SmRepositoryConfig_ 和 _Set-SmRepositoryConfig_ PowerShell cmdlet 来管理 MySQL 复制。

可以通过运行_Get-Help command_name_来获取有关可与 cmdlet 一起使用的参数及其描述的信息。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter软件 Cmdlet 参考指南"^]。

您必须了解与 MySQL HA 功能相关的限制：

* 两个节点以上不支持 NLB 和 MySQL HA。
* 不支持从SnapCenter独立安装切换到 NLB 安装或反之亦然，也不支持从 MySQL 独立安装切换到 MySQL HA。
* 如果从属存储库数据与主存储库数据不同步，则不支持自动故障转移。
+
您可以使用 _Set-SmRepositoryConfig_ cmdlet 启动强制故障转移。

* 当启动故障转移时，正在运行的作业可能会失败。
+
如果由于 MySQL 服务器或SnapCenter服务器关闭而发生故障转移，则任何正在运行的作业都可能失败。故障转移到第二个节点后，所有后续作业均成功运行。



有关配置高可用性的信息，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_NLB_and_ARR_with_SnapCenter["如何使用SnapCenter配置 NLB 和 ARR"^]。
