---
permalink: install/concept_create_and_manage_smb_shares.html 
sidebar: sidebar 
keywords: SMB shares 
summary: '要在存储虚拟机 (SVM) 上配置 SMB3 共享，您可以使用SnapCenter用户界面或 PowerShell cmdlet。' 
---
= 创建和管理 SMB 共享
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要在存储虚拟机 (SVM) 上配置 SMB3 共享，您可以使用SnapCenter用户界面或 PowerShell cmdlet。

|===


| *最佳实践：*建议使用 cmdlet，因为它使您能够利用SnapCenter提供的模板来自动化共享配置。 
|===
模板概括了卷和共享配置的最佳实践。您可以在 Windows 版SnapCenter插件包的安装文件夹中的 Templates 文件夹中找到这些模板。


TIP: 如果您愿意，您可以按照提供的模型创建自己的模板。在创建自定义模板之前，您应该查看 cmdlet 文档中的参数。



== 创建 SMB 共享

您可以使用SnapCenter共享页面在存储虚拟机 (SVM) 上创建 SMB3 共享。

您不能使用SnapCenter备份 SMB 共享上的数据库。  SMB 支持仅限于配置。

*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*共享*”。
. 从“存储虚拟机”下拉列表中选择 SVM。
. 单击“*新建*”。
+
“新共享”对话框打开。

. 在新建共享对话框中，定义共享：
+
|===
| 在这个领域... | 操作 


 a| 
描述
 a| 
输入共享的描述性文本。



 a| 
共享名称
 a| 
输入共享名称，例如 test_share。

您输入的共享名称也将用作卷名称。

共享名称：

** 必须是 UTF-8 字符串。
** 不得包含以下字符：从 0x00 到 0x1F（含）的控制字符、0x22（双引号）以及特殊字符 `\ / [ ] : (vertical bar) < > + = ; , ?`




 a| 
共享路径
 a| 
** 单击该字段以输入新的文件系统路径，例如 /。
** 双击该字段以从现有文件系统路径列表中进行选择。


|===
. 当您对输入的内容满意时，请单击“*确定*”。
+
SnapCenter在 SVM 上创建 SMB 共享。





== 删除 SMB 共享

当您不再需要 SMB 共享时，可以将其删除。

*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*共享*”。
. 在共享页面中，单击“*存储虚拟机*”字段以显示一个下拉菜单，其中包含可用存储虚拟机 (SVM) 的列表，然后选择要删除的共享的 SVM。
. 从 SVM 上的共享列表中，选择要删除的共享，然后单击“*删除*”。
. 在“删除共享”对话框中，单击“*确定*”。
+
SnapCenter从 SVM 中删除 SMB 共享。


