---
permalink: install/create-cluster-roles-asa-r2-resources.html 
sidebar: sidebar 
keywords: cluster role, privileges, asa r2 systems 
summary: 您应该为ASA r2 系统创建一个ONTAP集群角色，这样您就不必使用ONTAP管理员角色在SnapCenter中执行操作。 
---
= 为ASA r2 系统创建ONTAP集群角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应该创建具有最小权限的ONTAP集群角色，这样您就不必使用ONTAP管理员角色在SnapCenter中执行操作。您可以运行多个ONTAP CLI 命令来创建ONTAP集群角色并分配最低权限。

*步骤*

. 在存储系统上创建一个角色，并为该角色赋予所有权限。
+
`security login role create –vserver <cluster_name\>- role <role_name\> -cmddirname <permission\>`

+

NOTE: 您应该对每个权限重复此命令。

. 创建一个用户并将角色分配给该用户。
+
`security login create -user <user_name\> -vserver <cluster_name\> -application http -authmethod password -role <role_name\>`

. 解除用户锁定。
+
`security login unlock -user <user_name\> -vserver <cluster_name\>`





== 用于创建集群角色和分配权限的ONTAP CLI 命令

您应该运行几个ONTAP CLI 命令来创建集群角色并分配权限。

* `security login role create -vserver Cluster_name or cluster_name -role Role_Name -cmddirname "metrocluster show" -access readonly`
* `security login role create -vserver Cluster_name or cluster_name -role Role_Name -cmddirname "cluster identity modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster identity show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster peer show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "cluster show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "event generate-autosupport-log" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "job history show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "job show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "job stop" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup add" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup rename" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun igroup show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping add-reporting-nodes" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping remove-reporting-nodes" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun mapping show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun move-in-volume" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun offline" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun online" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun persistent-reservation clear" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun resize" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun serial" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "lun show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface create" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface delete" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface modify" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "network interface show" -access readonly`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme subsystem map" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme subsystem create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme subsystem delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme subsystem modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme subsystem host" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme subsystem controller" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme subsystem show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme namespace create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme namespace delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme namespace modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "nvme namespace show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "security login" -access readonly`
* `security login role create -role Role_Name -cmddirname "snapmirror create" -vserver Cluster_name -access all`
* `security login role create -role Role_Name -cmddirname "snapmirror list-destinations" -vserver Cluster_name -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy add-rule" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy modify-rule" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy remove-rule" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror policy show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror restore" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror show-history" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror update" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror update-ls-set" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license add" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license clean-up" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system license status show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system node modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system node show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "system status show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "version" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone split start" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume clone split stop" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume destroy" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume file clone create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume file show-disk-usage" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot modify-snaplock-expiry-time" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume offline" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume online" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume qtree show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume restrict" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot promote" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot rename" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot restore" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot restore-file" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume snapshot show-delta" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume unmount" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs share show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver cifs show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule create" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule delete" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy rule show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver export-policy show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver iscsi connection show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver modify" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "vserver show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "storage-unit show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "consistency-group" show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "snapmirror protect" show" -access all`
* `security login role create -vserver Cluster_name -role Role_Name -cmddirname "volume delete" show" -access all`

