---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks, create, manage, clustered disks, view 
summary: Windows 主机将存储系统上的 LUN 视为虚拟磁盘。您可以使用SnapCenter创建和配置 FC 连接或 iSCSI 连接的 LUN。 
---
= 创建和管理磁盘
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 主机将存储系统上的 LUN 视为虚拟磁盘。您可以使用SnapCenter创建和配置 FC 连接或 iSCSI 连接的 LUN。

* SnapCenter仅支持基本磁盘。不支持动态磁盘。
* 对于 GPT，只允许一个数据分区，对于 MBR，只允许一个主分区，该主分区具有一个使用 NTFS 或 CSVFS 格式化的卷和一个挂载路径。
* 支持的分区样式：GPT、MBR；在 VMware UEFI VM 中，仅支持 iSCSI 磁盘



NOTE: SnapCenter不支持重命名磁盘。如果重命名由SnapCenter管理的磁盘， SnapCenter操作将不会成功。



== 查看主机上的磁盘

您可以使用SnapCenter查看管理的每个 Windows 主机上的磁盘。

*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*磁盘*”。
. 从*主机*下拉列表中选择主机。
+
磁盘已列出。





== 查看集群磁盘

您可以查看使用SnapCenter管理的群集上的群集磁盘。仅当您从“主机”下拉菜单中选择集群时才会显示集群磁盘。

*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*磁盘*”。
. 从*主机*下拉列表中选择集群。
+
磁盘已列出。





== 建立 iSCSI 会话

如果您使用 iSCSI 连接到 LUN，则必须在创建 LUN 之前建立 iSCSI 会话以启用通信。

*开始之前*

* 您必须已将存储系统节点定义为 iSCSI 目标。
* 您必须已经在存储系统上启动了 iSCSI 服务。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["了解更多"^]


*关于此任务*

您只能在相同的 IP 版本之间建立 iSCSI 会话，无论是从 IPv6 到 IPv6，还是从 IPv4 到 IPv4。

仅当主机和目标位于同一子网中时，才可以使用链路本地 IPv6 地址进行 iSCSI 会话管理以及主机和目标之间的通信。

如果更改 iSCSI 启动器的名称，则对 iSCSI 目标的访问会受到影响。更改名称后，您可能需要重新配置启动器访问的目标，以便它们能够识别新名称。更改 iSCSI 启动器的名称后，必须确保重新启动主机。

如果您的主机有多个 iSCSI 接口，一旦您使用第一个接口上的 IP 地址建立了与SnapCenter 的iSCSI 会话，您就无法从具有不同 IP 地址的另一个接口建立 iSCSI 会话。

*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*iSCSI 会话*”。
. 从“存储虚拟机”下拉列表中，选择 iSCSI 目标的存储虚拟机 (SVM)。
. 从“*主机*”下拉列表中，选择会话的主机。
. 单击*建立会话*。
+
将显示“建立会话”向导。

. 在建立会话向导中，确定目标：
+
|===
| 在这个领域... | 进入... 


 a| 
目标节点名称
 a| 
iSCSI 目标的节点名称

如果存在现有的目标节点名称，则以只读格式显示该名称。



 a| 
目标门户地址
 a| 
目标网络门户的IP地址



 a| 
目标门户端口
 a| 
目标网络门户的TCP端口



 a| 
发起者门户地址
 a| 
发起者网络门户的 IP 地址

|===
. 当您对输入的内容满意时，请单击“连接”。
+
SnapCenter建立 iSCSI 会话。

. 重复此过程为每个目标建立会话。




== 创建 FC 连接或 iSCSI 连接的 LUN 或磁盘

Windows 主机将存储系统上的 LUN 视为虚拟磁盘。您可以使用SnapCenter创建和配置 FC 连接或 iSCSI 连接的 LUN。

如果您想在SnapCenter之外创建和格式化磁盘，则仅支持 NTFS 和 CSVFS 文件系统。

.开始之前
* 您必须已经在存储系统上为 LUN 创建了一个卷。
+
该卷应该仅保存 LUN，并且仅保存使用SnapCenter创建的 LUN。

+

NOTE: 除非克隆已被拆分，否则您无法在SnapCenter创建的克隆卷上创建 LUN。

* 您必须已在存储系统上启动 FC 或 iSCSI 服务。
* 如果您正在使用 iSCSI，则必须与存储系统建立 iSCSI 会话。
* 适用于 Windows 的SnapCenter插件包必须仅安装在要创建磁盘的主机上。


*关于此任务*

* 除非 Windows Server 故障转移群集中的主机共享 LUN，否则您无法将 LUN 连接到多个主机。
* 如果使用 CSV（群集共享卷）的 Windows Server 故障转移群集中的主机共享 LUN，则必须在拥有该群集组的主机上创建磁盘。


*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*磁盘*”。
. 从*主机*下拉列表中选择主机。
. 单击“*新建*”。
+
将打开创建磁盘向导。

. 在 LUN 名称页面中，识别 LUN：
+
|===
| 在这个领域... | 操作 


 a| 
存储系统
 a| 
选择 LUN 的 SVM。



 a| 
LUN 路径
 a| 
单击“浏览”以选择包含 LUN 的文件夹的完整路径。



 a| 
LUN 名称
 a| 
输入 LUN 的名称。



 a| 
簇大小
 a| 
选择集群的 LUN 块分配大小。

集群大小取决于操作系统和应用程序。



 a| 
LUN 标签
 a| 
或者，输入 LUN 的描述性文本。

|===
. 在磁盘类型页面中，选择磁盘类型：
+
|===
| 选择... | 条件 


 a| 
专用磁盘
 a| 
该 LUN 只能被一个主机访问。

忽略*资源组*字段。



 a| 
共享磁盘
 a| 
LUN 由 Windows Server 故障转移群集中的主机共享。

在“*资源组*”字段中输入集群资源组的名称。您只需在故障转移群集中的一个主机上创建磁盘。



 a| 
集群共享卷 (CSV)
 a| 
该 LUN 由使用 CSV 的 Windows Server 故障转移群集中的主机共享。

在“*资源组*”字段中输入集群资源组的名称。确保在其上创建磁盘的主机是群集组的所有者。

|===
. 在驱动器属性页面中，指定驱动器属性：
+
|===
| 财产 | 描述 


 a| 
自动分配挂载点
 a| 
SnapCenter根据系统驱动器自动分配卷挂载点。

例如，如果您的系统驱动器是 C:，则自动分配会在您的 C: 驱动器下创建一个卷装入点 (C:\scmnpt\)。共享磁盘不支持自动分配。



 a| 
分配驱动器号
 a| 
将磁盘安装到您在相邻下拉列表中选择的驱动器。



 a| 
使用卷挂载点
 a| 
将磁盘安装到您在相邻字段中指定的驱动器路径。

卷安装点的根目录必须由您正在创建磁盘的主机拥有。



 a| 
不要分配驱动器号或卷装入点
 a| 
如果您希望在 Windows 中手动安装磁盘，请选择此选项。



 a| 
LUN 大小
 a| 
指定 LUN 大小；最小 150 MB。

在相邻的下拉列表中选择 MB、GB 或 TB。



 a| 
对托管此 LUN 的卷使用精简配置
 a| 
精简配置 LUN。

精简配置一次仅分配所需的存储空间，从而使 LUN 能够高效地增长到最大可用容量。

确保卷上有足够的可用空间来容纳您认为需要的所有 LUN 存储。



 a| 
选择分区类型
 a| 
为 GUID 分区表选择 GPT 分区，或为主引导记录选择 MBR 分区。

MBR 分区可能会导致 Windows Server 故障转移群集中出现错位问题。


NOTE: 不支持统一可扩展固件接口 (UEFI) 分区磁盘。

|===
. 在映射 LUN 页面中，选择主机上的 iSCSI 或 FC 启动器：
+
|===
| 在这个领域... | 操作 


 a| 
主机
 a| 
双击群集组名称，显示属于该群集的主机的下拉列表，然后选择启动器的主机。

仅当 LUN 由 Windows Server 故障转移群集中的主机共享时，才会显示此字段。



 a| 
选择主机发起者
 a| 
选择“*光纤通道*”或“*iSCSI*”，然后选择主机上的启动器。

如果您使用具有多路径 I/O (MPIO) 的 FC，则可以选择多个 FC 启动器。

|===
. 在“组类型”页面中，指定是否要将现有 igroup 映射到 LUN，还是创建新的 igroup：
+
|===
| 选择... | 条件 


 a| 
为选定的启动器创建新的 igroup
 a| 
您想要为选定的启动器创建一个新的 igroup。



 a| 
为选定的启动器选择现有的 igroup 或指定新的 igroup
 a| 
您想要为选定的启动器指定一个现有的 igroup，或者使用您指定的名称创建一个新的 igroup。

在 *igroup name* 字段中输入 igroup 名称。输入现有 igroup 名称的前几个字母以自动完成该字段。

|===
. 在“摘要”页面中，检查您的选择，然后单击“完成”。
+
SnapCenter创建 LUN 并将其连接到主机上的指定驱动器或驱动器路径。





== 调整磁盘大小

您可以根据存储系统需求的变化增加或减少磁盘的大小。

*关于此任务*

* 对于精简配置的 LUN， ONTAP LUN 几何大小显示为最大大小。
* 对于厚置备 LUN，可扩展大小（卷中的可用大小）显示为最大大小。
* 具有 MBR 样式分区的 LUN 的大小限制为 2 TB。
* 具有 GPT 样式分区的 LUN 的存储系统大小限制为 16 TB。
* 在调整 LUN 大小之前制作快照是一个好主意。
* 如果您需要从调整 LUN 大小之前创建的快照中恢复 LUN， SnapCenter会自动将 LUN 调整为快照的大小。
+
恢复操作后，必须从调整大小后创建的快照中恢复调整大小后添加到 LUN 的数据。



*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*磁盘*”。
. 从主机下拉列表中选择主机。
+
磁盘已列出。

. 选择要调整大小的磁盘，然后单击“调整大小”。
. 在“调整磁盘大小”对话框中，使用滑块工具指定磁盘的新大小，或在“大小”字段中输入新大小。
+

NOTE: 如果您手动输入尺寸，则需要单击“尺寸”字段外部，然后才能正确启用“收缩”或“扩展”按钮。此外，您必须单击 MB、GB 或 TB 来指定测量单位。

. 当您对输入的内容满意时，请根据需要单击“*收缩*”或“*扩展*”。
+
SnapCenter调整磁盘大小。





== 连接磁盘

您可以使用连接磁盘向导将现有 LUN 连接到主机，或者重新连接已断开连接的 LUN。

.开始之前
* 您必须已在存储系统上启动 FC 或 iSCSI 服务。
* 如果您正在使用 iSCSI，则必须与存储系统建立 iSCSI 会话。
* 除非 Windows Server 故障转移群集中的主机共享 LUN，否则您无法将 LUN 连接到多个主机。
* 如果 LUN 由使用 CSV（群集共享卷）的 Windows Server 故障转移群集中的主机共享，则必须连接拥有群集组的主机上的磁盘。
* 仅需在连接磁盘的主机上安装适用于 Windows 的插件。


*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*磁盘*”。
. 从*主机*下拉列表中选择主机。
. 单击“连接”。
+
将打开连接磁盘向导。

. 在 LUN 名称页面中，确定要连接的 LUN：
+
|===
| 在这个领域... | 操作 


 a| 
存储系统
 a| 
选择 LUN 的 SVM。



 a| 
LUN 路径
 a| 
单击“浏览”以选择包含 LUN 的卷的完整路径。



 a| 
LUN 名称
 a| 
输入 LUN 的名称。



 a| 
簇大小
 a| 
选择集群的 LUN 块分配大小。

集群大小取决于操作系统和应用程序。



 a| 
LUN 标签
 a| 
或者，输入 LUN 的描述性文本。

|===
. 在磁盘类型页面中，选择磁盘类型：
+
|===
| 选择... | 条件 


 a| 
专用磁盘
 a| 
该 LUN 只能被一个主机访问。



 a| 
共享磁盘
 a| 
LUN 由 Windows Server 故障转移群集中的主机共享。

您只需将磁盘连接到故障转移群集中的一台主机。



 a| 
集群共享卷 (CSV)
 a| 
该 LUN 由使用 CSV 的 Windows Server 故障转移群集中的主机共享。

确保连接到磁盘的主机是群集组的所有者。

|===
. 在驱动器属性页面中，指定驱动器属性：
+
|===
| 财产 | 描述 


 a| 
自动分配
 a| 
让SnapCenter根据系统驱动器自动分配卷挂载点。

例如，如果您的系统驱动器是 C:，则自动分配属性会在您的 C: 驱动器下创建一个卷装入点 (C:\scmnpt\)。共享磁盘不支持自动分配属性。



 a| 
分配驱动器号
 a| 
将磁盘安装到您在相邻下拉列表中选择的驱动器。



 a| 
使用卷挂载点
 a| 
将磁盘安装到您在相邻字段中指定的驱动器路径。

卷安装点的根目录必须由您正在创建磁盘的主机拥有。



 a| 
不要分配驱动器号或卷装入点
 a| 
如果您希望在 Windows 中手动安装磁盘，请选择此选项。

|===
. 在映射 LUN 页面中，选择主机上的 iSCSI 或 FC 启动器：
+
|===
| 在这个领域... | 操作 


 a| 
主机
 a| 
双击集群组名称，显示属于该集群的主机的下拉列表，然后选择启动器的主机。

仅当 LUN 由 Windows Server 故障转移群集中的主机共享时，才会显示此字段。



 a| 
选择主机发起者
 a| 
选择“*光纤通道*”或“*iSCSI*”，然后选择主机上的启动器。

如果您使用带有 MPIO 的 FC，则可以选择多个 FC 启动器。

|===
. 在“组类型”页面中，指定是否要将现有 igroup 映射到 LUN 或创建新的 igroup：
+
|===
| 选择... | 条件 


 a| 
为选定的启动器创建新的 igroup
 a| 
您想要为选定的启动器创建一个新的 igroup。



 a| 
为选定的启动器选择现有的 igroup 或指定新的 igroup
 a| 
您想要为选定的启动器指定一个现有的 igroup，或者使用您指定的名称创建一个新的 igroup。

在 *igroup name* 字段中输入 igroup 名称。输入现有 igroup 名称的前几个字母以自动完成该字段。

|===
. 在“摘要”页面中，检查您的选择并单击“完成”。
+
SnapCenter将 LUN 连接到主机上的指定驱动器或驱动器路径。





== 断开磁盘

您可以将 LUN 与主机断开连接，而不会影响 LUN 的内容，但有一个例外：如果在克隆分离之前断开连接，则会丢失克隆的内容。

.开始之前
* 确保 LUN 未被任何应用程序使用。
* 确保 LUN 未被监控软件监控。
* 如果 LUN 是共享的，请确保从 LUN 中删除集群资源依赖关系，并验证集群中的所有节点是否都已打开电源、正常运行且可供SnapCenter使用。


*关于此任务*

如果断开SnapCenter创建的FlexClone卷中的某个 LUN 且该卷上没有连接任何其他 LUN，SnapCenter会删除该卷。在断开 LUN 之前， SnapCenter会显示一条消息，警告您FlexClone卷可能会被删除。

为避免自动删除FlexClone卷，您应该在断开最后一个 LUN 之前重命名该卷。重命名卷时，请确保更改多个字符，而不仅仅是名称中的最后一个字符。

*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*磁盘*”。
. 从*主机*下拉列表中选择主机。
+
磁盘已列出。

. 选择要断开的磁盘，然后单击“*断开连接*”。
. 在“断开磁盘”对话框中，单击“*确定*”。
+
SnapCenter断开磁盘连接。





== 删除磁盘

当您不再需要磁盘时，可以将其删除。删除磁盘后，将无法恢复。

*步骤*

. 在左侧导航窗格中，单击“*主机*”。
. 在“主机”页面中，单击“*磁盘*”。
. 从*主机*下拉列表中选择主机。
+
磁盘已列出。

. 选择要删除的磁盘，然后单击“*删除*”。
. 在“删除磁盘”对话框中，单击“确定”。
+
SnapCenter删除磁盘。


