---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: 为要备份的 Unix 文件系统创建备份策略。 
---
= 为 Unix 文件系统创建备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter备份 Unix 文件系统之前，您必须为要备份的资源或资源组创建备份策略。备份策略是一组规则，用于控制如何管理、安排和保留备份。您还可以指定复制、脚本和备份类型设置。当您想要在另一个资源或资源组上重复使用策略时，创建策略可以节省时间。

.开始之前
* 您必须已完成安装SnapCenter、添加主机、发现文件系统和创建存储系统连接等任务，为数据保护做好准备。
* 如果您要将快照复制到镜像或保管库二级存储， SnapCenter管理员必须已为您分配源卷和目标卷的 SVM。
* 查看SnapMirror主动同步特定的先决条件和限制。欲了解详细信息，请参阅 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror主动同步的对象限制"]。


.关于此任务
* SnapLock
+
** 如果选择了“保留备份副本特定天数”选项，则SnapLock保留期必须小于或等于上述保留天数。
+
指定快照锁定期可防止在保留期到期之前删除快照。这可能导致保留的快照数量超过策略中指定的数量。

+
对于ONTAP 9.12.1 及以下版本、作为恢复的一部分从SnapLock Vault 快照创建的克隆将继承SnapLock Vault 到期时间。存储管理员应在SnapLock到期后手动清理克隆。





.步骤
. 在左侧导航窗格中，单击“*设置*”。
. 在“设置”页面中，单击“*策略*”。
. 从下拉列表中选择“*Unix 文件系统*”。
. 单击“*新建*”。
. 在名称页面中，输入策略名称和详细信息。
. 在“备份和复制”页面中，执行以下操作：
+
.. 指定备份设置。
.. 通过选择*按需*、*每小时*、*每天*、*每周*或*每月*来指定计划频率。
.. 在“选择辅助复制选项”部分中，选择以下一个或两个辅助复制选项：


+
|===
| 对于这个领域... | 操作 


 a| 
创建本地 Snapshot 副本后更新SnapMirror
 a| 
选择此字段可在另一个卷上创建备份集的镜像副本（SnapMirror复制）。

应为SnapMirror主动同步启用此选项。



 a| 
创建本地 Snapshot 副本后更新SnapVault
 a| 
选择此选项可执行磁盘到磁盘备份复制（SnapVault备份）。



 a| 
错误重试次数
 a| 
输入操作停止之前允许的最大复制尝试次数。

|===
. 在“保留”页面中，指定“备份和复制”页面中选择的备份类型和计划类型的保留设置：
+
|===


| 目的 | 操作 


 a| 
保留一定数量的快照
 a| 
选择*要保留的副本*，然后指定要保留的快照数量。

如果快照数量超过指定数量，则会删除快照，并首先删除最旧的副本。


NOTE: 最大保留值为 1018。如果保留设置的值高于底层ONTAP版本支持的值，则备份将失败。


IMPORTANT: 如果您计划启用SnapVault复制，则必须将保留计数设置为 2 或更高。如果将保留计数设置为 1，则保留操作可能会失败，因为第一个快照是SnapVault关系的参考快照，直到较新的快照复制到目标。



 a| 
将快照保留一定天数
 a| 
选择*保留副本*，然后指定在删除快照之前要保留快照的天数。



 a| 
快照副本锁定期
 a| 
选择*Snapshot 副本锁定期限*并指定天、月或年的持续时间。

Snaplock 保留期应少于 100 年。

|===
. 选择策略标签。
+

NOTE: 您可以为远程复制的主快照分配SnapMirror标签，从而允许主快照将快照复制操作从SnapCenter卸载到ONTAP二级系统。无需在策略页面中启用SnapMirror或SnapVault选项即可完成此操作。

. 在脚本页面中，分别输入要在备份操作之前或之后运行的前置脚本或后置脚本的路径和参数。
+

NOTE: 您应该检查这些命令是否存在于插件主机上可用的命令列表中，该列表位于 _ NetApp路径下。

+
您还可以指定脚本超时值。默认值是 60 秒。

. 查看摘要，然后单击“*完成*”。

