---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: 在添加主机和安装插件包之前，您必须完成所有要求。  NetApp支持的插件可以在 Windows、Linux 或 AIX 环境中使用。 
---
= 添加主机并安装 Windows、Linux 或 AIX 插件包的先决条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在添加主机和安装插件包之前，您必须完成所有要求。  NetApp支持的插件在 Windows、Linux 和 AIX 环境中均受支持。


NOTE: AIX 支持存储和 Oracle 应用程序。

* 您必须在 Linux、Windows 或 AIX 主机上安装 Java 11。
+

NOTE: IBM Java 在 Windows 和 Linux 主机上不受支持。

* 在 Windows 主机上安装插件时，如果指定非内置的凭据，或者用户属于本地工作组用户，则必须在主机上禁用 UAC。
* 执行添加主机操作的客户端主机上必须提供NetApp支持的插件，如 MongoDB、ORASCPM、Oracle 应用程序、SAP ASE、SAP MaxDB 和存储插件。




== 常规

如果您正在使用 iSCSI，则 iSCSI 服务应该正在运行。



== Windows 主机

* 您必须拥有具有本地管理员权限的域用户，并在远程主机上拥有本地登录权限。
* 如果您在SnapCenter中管理集群节点，则必须拥有对集群中所有节点具有管理权限的用户。
* 您必须手动选择适用于 Microsoft Windows 的SnapCenter插件。
+
http://www.java.com/en/download/manual.jsp["下载适用于 Windows 的 JAVA"]





== Linux 和 AIX 主机


NOTE: AIX 支持存储和 Oracle 应用程序。

* 您必须为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须在 Linux 主机上安装 Java 11。
+
如果您使用 Windows Server 2019 或 Windows Server 2016 作为SnapCenter Server 主机，则必须安装 Java 11。互操作性矩阵工具 (IMT) 包含有关要求的最新信息。

+
http://www.java.com/en/download/manual.jsp["下载适用于 Linux 的 JAVA"]

+
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?license=IBM["下载适用于 AIX 的 JAVA"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp 互操作性表工具"]

* 您必须为非 root 用户配置 sudo 权限以提供对多个路径的访问权限。使用 visudo Linux 实用程序将以下行添加到 /etc/sudoers 文件。
+

NOTE: 确保您使用的是 Sudo 版本 1.8.7 或更高版本。

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_ 是您创建的非 root 用户的名称。

+
您可以从 *sc_unix_plugins_checksum.txt* 文件中获取 _checksum_value_，该文件位于：

+
** _C:\ProgramData\ NetApp\ SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_（如果SnapCenter Server 安装在 Windows 主机上）。
** _/opt/ NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ 如果SnapCenter Server 安装在 Linux 主机上。
+

IMPORTANT: 该示例仅应作为创建您自己的数据的参考。







== AIX 主机要求

在安装适用于 AIX 的SnapCenter插件包之前，您应该确保主机满足要求。


NOTE: AIX 支持存储和 Oracle 应用程序。


NOTE: SnapCenter Plug-in for UNIX 是SnapCenter Plug-ins Package for AIX 的一部分，不支持并发卷组。

|===
| 物品 | 要求 


 a| 
操作系统
 a| 
AIX 7.1 或更高版本



 a| 
主机上SnapCenter插件的最小 RAM
 a| 
4 GB



 a| 
主机上SnapCenter插件的最小安装和日志空间
 a| 
2 GB


NOTE: 您应该分配足够的磁盘空间并监控日志文件夹的存储消耗。所需的日志空间取决于要保护的实体的数量和数据保护操作的频率。如果没有足够的磁盘空间，则不会为最近运行的操作创建日志。



 a| 
所需的软件包
 a| 
Java 11 IBM Java

如果您已将 JAVA 升级到最新版本，则必须确保位于 /var/opt/snapcenter/spl/etc/spl.properties 的 JAVA_HOME 选项设置为正确的 JAVA 版本和正确的路径。

|===
有关受支持版本的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["NetApp 互操作性表工具"^]。



=== 为 AIX 主机的非 root 用户配置 sudo 权限

SnapCenter 4.4 及更高版本允许非 root 用户安装适用于 AIX 的SnapCenter插件包并启动插件进程。插件进程将以有效的非 root 用户身份运行。您应该为非 root 用户配置 sudo 权限以提供对多个路径的访问。

*您需要什么*

* Sudo 版本 1.8.7 或更高版本。
* 编辑_/etc/ssh/sshd_config_文件，配置消息认证码算法：MACs hmac-sha2-256、MACs hmac-sha2-512。
+
更新配置文件后重新启动sshd服务。

+
示例：

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*关于此任务*

您应该为非 root 用户配置 sudo 权限以提供对以下路径的访问权限：

* /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx
* /custom_location/ NetApp/snapcenter/spl/安装/插件/卸载
* /custom_location/ NetApp/snapcenter/spl/bin/spl


*步骤*

. 登录到要安装适用于 AIX 的SnapCenter插件包的 AIX 主机。
. 使用 visudo Linux 实用程序将以下行添加到 /etc/sudoers 文件。
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+

NOTE: 如果您有 RAC 设置，以及其他允许的命令，您应该将以下内容添加到 /etc/sudoers 文件：“/<crs_home>/bin/olsnodes”



您可以从_/etc/oracle/olr.loc_文件中获取_crs_home_的值。

_AIX_USER_ 是您创建的非 root 用户的名称。

您可以从 *sc_unix_plugins_checksum.txt* 文件中获取 _checksum_value_，该文件位于：

* _C:\ProgramData\ NetApp\ SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_（如果SnapCenter Server 安装在 Windows 主机上）。
* _/opt/ NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ 如果SnapCenter Server 安装在 Linux 主机上。



IMPORTANT: 该示例仅应作为创建您自己的数据的参考。
