---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: 在使用SnapCenter之前，了解与要执行的备份、克隆和还原操作相关的基本概念会很有帮助。 
---
= 数据保护的关键概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter之前，请了解备份、克隆和还原的关键概念。



== 资源

资源包括数据库、Windows 文件系统或使用SnapCenter备份或克隆的文件共享。根据您的环境，资源也可能是数据库实例、SQL Server 可用性组、Oracle 数据库、RAC 数据库或自定义应用程序组。



== 资源组

资源组是主机或集群上的资源集合，可能来自多个主机和集群。对资源组执行的操作将根据指定的计划应用于其所有资源。您可以对单个资源或组执行按需或计划备份。


NOTE: 如果共享资源组中的一个主机进入维护模式，则该组的所有主机上的所有计划操作都将暂停。

使用相关插件来备份特定资源：数据库插件用于数据库，文件系统插件用于文件系统，以及SnapCenter Plug-in for VMware vSphere用于虚拟机和数据存储区。



== 策略

策略指定备份频率、副本保留、复制、脚本和数据保护操作的其他特征。

创建资源组或执行按需备份时可以选择一个或多个策略。

资源组定义需要保护什么以及何时（以日期和时间为单位）进行保护。政策描述了如何实施保护。例如，如果需要备份主机的所有数据库或文件系统，则可以创建包含主机中所有数据库或文件系统的资源组。然后可以将两个策略附加到资源组：每日策略和每小时策略。

创建资源组并附加策略时，可以将其配置为每天执行一次完整备份，并每小时执行一次日志备份的另一个计划。

自定义处方和附言可用于数据保护操作。这些脚本允许在数据保护作业之前或之后实现自动化。例如，脚本可以自动通知数据保护作业失败或警告。在制定前言和后记之前，了解创建这些脚本的要求至关重要。



== 前言和后记的使用

自定义的处方和后记可以在作业之前或之后自动执行数据保护任务。例如，您可以添加一个脚本来通知您作业失败或警告。在设置它们之前，请确保您了解这些脚本的要求。



=== 支持的脚本类型

Windows 支持以下类型的脚本：

* 批处理文件
* PowerShell 脚本
* Perl 脚本


UNIX 支持以下类型的脚本：

* Perl 脚本
* Python 脚本
* Shell 脚本
+

NOTE: 除了默认的 bash shell 之外，还支持其他 shell，如 sh-shell、k-shell 和 c-shell。





=== 脚本路径

作为非虚拟化和虚拟化存储系统上的SnapCenter操作的一部分运行的所有前脚本和后脚本都在插件主机上执行。

* Windows 脚本应位于插件主机上。



NOTE: 前言或后记路径不应包含驱动器或共享。该路径应相对于 SCRIPTS_PATH。

* UNIX 脚本应位于插件主机上。



NOTE: 脚本路径在执行时进行验证。



=== 在哪里指定脚本

脚本在备份策略中指定。当备份作业开始时，策略会自动将脚本与正在备份的资源关联起来。创建备份策略时，您可以指定前言和后记参数。


NOTE: 您不能指定多个脚本。



=== 脚本超时

默认情况下，超时设置为 60 秒。您可以修改超时值。



=== 脚本输出

Windows 脚本和后记输出文件的默认目录是 Windows\System32。

UNIX 前言和后记没有默认位置。您可以将输出文件重定向到任何首选位置。
