---
permalink: get-started/concept_disaster_recovery.html 
sidebar: sidebar 
keywords: Disaster Recovery, DR, crash, resource deleted 
summary: 当发生资源损坏或服务器崩溃等灾难时，您可以使用SnapCenter灾难恢复功能恢复SnapCenter服务器。 
---
= SnapCenter中的灾难恢复
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter灾难恢复 (DR) 功能可让您从资源损坏或服务器崩溃等灾难中恢复。它有助于恢复SnapCenter存储库、服务器计划、配置组件以及 SQL Server 的SnapCenter插件及其存储。

本节介绍SnapCenter中的两种 DR 类型：



== SnapCenter服务器灾难恢复

* SnapCenter Server 数据已备份，无需在SnapCenter Server 上添加或管理任何插件即可恢复。
* 辅助SnapCenter服务器应安装在与主SnapCenter服务器相同的安装目录和端口上。
* 对于多重身份验证 (MFA)，在SnapCenter Server DR 期间，关闭所有浏览器选项卡并重新打开浏览器以再次登录。这将清除现有或活动的会话 cookie 并更新正确的配置数据。
* SnapCenter灾难恢复功能使用 REST API 来备份SnapCenter服务器。看link:../tech-refresh/task_tech_refresh_server_host.html["用于SnapCenter Server 灾难恢复的 REST API 工作流"] 。
* 审核设置相关的配置文件未在 DR 备份中备份，还原操作后也不会在 DR 服务器上备份。您应该手动重复审计日志设置。




== SnapCenter插件和存储灾难恢复

DR 仅适用于 SQL Server 的SnapCenter插件。如果插件关闭，请切换到另一个 SQL 主机并按照以下几个步骤恢复数据。看link:../protect-scsql/task_disaster_recovery_scsql.html["SnapCenter插件 for SQL Server 的灾难恢复"] 。

SnapCenter使用ONTAP SnapMirror复制数据，通过将数据同步到辅助站点，可以用于 DR。要启动故障转移，请中断SnapMirror复制。在回退期间，逆转同步以将数据从 DR 站点复制回主位置。
