---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: 凭证根据应用程序或环境使用不同的身份验证方法。凭据对用户进行身份验证，以便他们可以执行SnapCenter操作。您应该创建一组用于安装插件的凭据和另一组用于数据保护操作的凭据。 
---
= SnapCenter凭据的身份验证方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
凭证根据应用程序或环境使用不同的身份验证方法。凭据对用户进行身份验证，以便他们可以执行SnapCenter操作。您应该创建一组用于安装插件的凭据，并创建另一组用于数据保护操作的凭据。



== Windows 身份验证

Windows 身份验证方法针对 Active Directory 进行身份验证。对于 Windows 身份验证，Active Directory 是在SnapCenter之外设置的。 SnapCenter无需额外配置即可进行身份验证。您需要 Windows 凭证来添加主机、安装插件包和安排作业。



== 不受信任的域身份验证

SnapCenter允许属于不受信任域的用户和组创建 Windows 凭据。为了使身份验证成功，您应该向SnapCenter注册不受信任的域。



== 本地工作组身份验证

SnapCenter允许使用本地工作组用户和组创建 Windows 凭据。本地工作组用户和组的 Windows 身份验证不会在 Windows 凭据创建期间发生，而是会推迟到主机注册和其他主机操作执行时发生。



== SQL Server 身份验证

SQL 身份验证方法针对 SQL Server 实例进行身份验证。这意味着必须在SnapCenter中发现 SQL Server 实例。因此，添加SQL凭证前，必须先添加主机、安装插件包、刷新资源。您需要 SQL Server 身份验证才能执行 SQL Server 上的调度或发现资源等操作。



== Linux 身份验证

Linux 身份验证方法针对 Linux 主机进行身份验证。在从SnapCenter GUI 远程添加 Linux 主机和安装适用于 Linux 的SnapCenter插件包的初始步骤中，您需要进行 Linux 身份验证。



== AIX 身份验证

AIX 身份验证方法针对 AIX 主机进行身份验证。在从SnapCenter GUI 远程添加 AIX 主机和安装 AIX的 SnapCenter插件包的初始步骤中，您需要进行 AIX 身份验证。



== Oracle 数据库身份验证

Oracle 数据库身份验证方法针对 Oracle 数据库进行身份验证。如果数据库主机上禁用了操作系统 (OS) 身份验证，则需要 Oracle 数据库身份验证才能在 Oracle 数据库上执行操作。因此，在添加 Oracle 数据库凭证之前，您应该在 Oracle 数据库中创建具有 sysdba 权限的 Oracle 用户。



== Oracle ASM 身份验证

Oracle ASM 身份验证方法针对 Oracle 自动存储管理 (ASM) 实例进行身份验证。如果您需要访问 Oracle ASM 实例并且数据库主机上禁用了 OS 身份验证，则需要进行 Oracle ASM 身份验证。在添加 Oracle ASM 凭据之前，请在 ASM 实例中创建具有系统权限的 Oracle 用户。



== RMAN 目录身份验证

RMAN 目录身份验证方法针对 Oracle Recovery Manager (RMAN) 目录数据库进行身份验证。如果您已经配置了外部目录机制并将您的数据库注册到目录数据库，则需要添加 RMAN 目录身份验证。
