---
permalink: get-started/reference_data_security.html 
sidebar: sidebar 
keywords: security, authentication, CA certificates, FIPS, SSL, AES, TLS, RBAC, MFA, multi-factor authentication 
summary: SnapCenter采用严格的安全和身份验证功能，确保您的数据安全。 
---
= SnapCenter中的安全功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter采用严格的安全和身份验证功能，确保您的数据安全。

SnapCenter包含以下安全功能：

* 与SnapCenter的所有通信都使用 HTTP over SSL (HTTPS)。
* SnapCenter中的所有凭据均使用高级加密标准 (AES) 加密进行保护。
* 支持符合联邦信息处理标准 (FIPS) 的安全算法。
* 支持使用客户提供的授权CA证书。
* 支持传输层安全性 (TLS) 1.3 以便与ONTAP进行通信。您还可以使用 TLS 1.2 进行客户端和服务器之间的通信。
* 支持一组特定的 SSL 密码套件，以提供跨网络通信的安全性。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["了解更多"] 。
* SnapCenter安装在您公司的防火墙内，以启用对SnapCenter服务器的访问并启用SnapCenter服务器和插件之间的通信。
* SnapCenter API 和操作访问使用 AES 加密的令牌，该令牌在 24 小时后过期。
* SnapCenter与 Windows Active Directory 集成，用于登录和基于角色的访问控制 (RBAC) 来管理访问权限。
* 适用于 Windows 和 Linux 主机的ONTAP上的SnapCenter支持 IPsec。 https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["了解更多"] 。
* SnapCenter PowerShell cmdlet 是会话安全的。
* 默认 15 分钟不活动时间后， SnapCenter会警告您将在 5 分钟后被注销。
+
20 分钟不活动后， SnapCenter会将您注销，您必须重新登录。您可以修改注销期限。

* 5 次登录尝试失败后，登录将被暂时禁用。
* 支持SnapCenter Server 和ONTAP之间的 CA 证书认证。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["了解更多"] 。
* 完整性验证器被添加到SnapCenter服务器和插件中，并在全新安装和升级操作期间验证所有附带的二进制文件。




== CA证书概述

SnapCenter Server 安装程序在安装期间启用集中式 SSL 证书支持。为了增强服务器和插件之间的安全通信， SnapCenter支持使用客户提供的授权 CA 证书。

安装SnapCenter服务器和相应的插件后，您应该部署 CA 证书。有关更多信息，请参阅link:../install/reference_generate_CA_certificate_CSR_file.html["生成CA证书CSR文件"] 。

您还可以为 VMware vSphere 的SnapCenter插件部署 CA 证书。有关更多信息，请参阅 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_and_import_certificates.html["创建并导入证书"^] 。



== 双向 SSL 通信

双向 SSL 通信确保SnapCenter服务器和插件之间的相互通信安全。



== 基于证书的身份验证概述

基于证书的身份验证可验证尝试访问SnapCenter插件主机的各个用户的真实性。用户应导出不带私钥的SnapCenter服务器证书并将其导入插件主机受信任存储区。仅当启用双向 SSL 功能时，基于证书的身份验证才有效。



== 多重身份验证 (MFA)

MFA 通过安全断言标记语言 (SAML) 使用第三方身份提供者 (IdP) 来管理用户会话。此功能通过选择使用多种因素（例如 TOTP、生物识别、推送通知等）以及现有的用户名和密码来增强身份验证的安全性。此外，它还使客户能够使用自己的用户身份提供商在其产品组合中获得统一的用户登录（SSO）。

MFA 仅适用于SnapCenter Server UI 登录。登录通过 IdP Active Directory 联合身份验证服务 (AD FS) 进行身份验证。您可以在 AD FS 配置各种身份验证因素。 SnapCenter是服务提供商，您应该将SnapCenter配置为 AD FS 中的依赖方。要在SnapCenter中启用 MFA，您将需要 AD FS 元数据。

有关启用 MFA 的信息，请参阅link:../install/enable_multifactor_authentication.html["启用多重身份验证"]。
