---
permalink: protect-mysql/install-the-snapcenter-plug-in-for-mysql-on-linux-hosts-using-the-command-line-interface.html 
sidebar: sidebar 
keywords: install, SnapCenter Plug-in for MySQL 
summary: '您应该使用SnapCenter用户界面 (UI) 安装适用于 MySQL 数据库的SnapCenter插件。如果您的环境不允许从SnapCenter UI 远程安装插件，您可以使用命令行界面 (CLI1) 以控制台模式或静默模式安装 MySQL 数据库插件。' 
---
= 使用命令行界面在 Linux 主机上安装适用于 MySQL 的SnapCenter插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应该使用SnapCenter用户界面 (UI) 安装适用于 MySQL 数据库的SnapCenter插件。如果您的环境不允许从SnapCenter UI 远程安装插件，您可以使用命令行界面 (CLI) 以控制台模式或静默模式安装 MySQL 数据库插件。

.开始之前
* 您应该在每个必须保护 MySQL 实例的 Linux 主机上安装 MySQL 数据库插件。
* 要安装 MySQL 数据库的SnapCenter插件的 Linux 主机必须满足相关软件、数据库和操作系统要求。
+
互操作性矩阵工具 (IMT) 包含有关受支持配置的最新信息。

+
https://imt.netapp.com/matrix/imt.jsp?components=121070;&solution=1259&isHWU&src=IMT["NetApp 互操作性表工具"]

* 适用于 MySQL 数据库的SnapCenter插件是适用于 Linux 的SnapCenter插件包的一部分。在安装适用于 Linux 的SnapCenter插件包之前，您应该已经在 Windows 主机上安装了SnapCenter 。


.步骤
. 将 Linux 安装文件 (snapcenter_linux_host_plugin.bin) 的SnapCenter插件包从 C:\ProgramData\ NetApp\ SnapCenter\Package Repository 复制到要安装 MySQL 插件的主机。
+
您可以从安装了SnapCenter服务器的主机访问此路径。

. 从命令提示符处，导航到复制安装文件的目录。
. 安装插件： `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
+
** -DPORT 指定 SMCore HTTPS 通信端口。
** -DSERVER_IP 指定SnapCenter服务器 IP 地址。
** -DSERVER_HTTPS_PORT 指定SnapCenter服务器 HTTPS 端口。
** -DUSER_INSTALL_DIR 指定要安装 Linux 版SnapCenter插件包的目录。
** DINSTALL_LOG_NAME 指定日志文件的名称。


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. 编辑 /<安装目录> NetApp文件，然后添加 PLUGINS_ENABLED = MySQL:3.0 参数。
. 使用 Add-Smhost cmdlet 和所需参数将主机添加到SnapCenter服务器。
+
可以通过运行_Get-Help command_name_来获取有关可与命令一起使用的参数及其描述的信息。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter软件 Cmdlet 参考指南"^]。


